### ISSUE TITLE
Fastbot 能否不重启，而是跳到首页或指定页面继续任务？

### ISSUE THREAD

**Issue by omigo** [bytedance/Fastbot_Android#101]
Fastbot 会杀掉APP，然后 RESTART，然而我的需求是要在一次打开app中完成Monkey任务。Fastbot 能否不重启，而是跳到首页或指定页面继续任务？

**Comment by adisonhyh** [comment]
同问

**Comment by omigo** [comment]
不可以吗，凭我粗浅的理解，这应该只是一个配置问题啊， 应该能实现吧？

**Comment by zhangzhao4444** [comment]
OK 已记录需求，后面排期优化下。提供配置不restart。

**Comment by zhangzhao4444** [comment]
https://github.com/bytedance/Fastbot_Android/issues/136 看可以通过配置这个方式来实现需求吗
