### ISSUE TITLE
多台设备运行脚本后，文件管理器打不开，提示“连接已断开”“找不到sd卡”

### ISSUE THREAD

**Issue by astrid77** [bytedance/Fastbot_Android#103]
设备：魅族18 Pro、华为 nova 2s、一加8T、三星 A52、OPPO reno 5
麻烦看看是什么问题呢？目前只能通过恢复出厂设置解决。。

**Comment by astrid77** [comment]
另外，是否有命令能让脚本不操作音量键呢？经常运行期间播放视频的时候声音被加到最大。。。

**Comment by zhangzhao4444** [comment]
音量只能插耳机来解决，另外第一个文件管理器打不开是这些设备都有问题？？

**Comment by astrid77** [comment]
@zhangzhao4444 多谢回复～
戴耳机是可以的😂我也没想到其他方式。
文件管理器打不开都是在执行脚本之后才出现的问题，手机开始都是正常的。
运行期间只是执行自动化脚本和adb命令，没有其他操作，刚开始用了几根接触不良的数据线，不知道有没有可能是这个问题。
官方用这个脚本执行的时候没有遇到这个问题吗？

**Comment by zhangzhao4444** [comment]
没有遇到这个问题。暂时先close，后面再观察下
