### ISSUE TITLE
配置 max.xpath.actions 自定义事件未执行成功

### ISSUE THREAD

**Issue by mengdg** [bytedance/Fastbot_Android#108]
`
[
{
	"prob": 1,
	"activity": "com.soft.blued.ui.login_register.SignInActivity",
	"times": 1,
	"actions": [
		{
			"xpath":"/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/androidx.viewpager.widget.ViewPager/android.widget.LinearLayout/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.FrameLayout[2]/android.widget.EditText",
			"action": "CLICK",
			"text": "18518230989",
			"clearText": true,
			"throttle": 3000
		},
		{
			"xpath":"/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/androidx.viewpager.widget.ViewPager/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.EditText",
			"action": "CLICK",
			"text": "Mdg123456",
			"clearText": false,
			"throttle": 3000
		},
		{
			"xpath": "//*[@resource-id='com.soft.blued:id/tv_login' and @text='登录']",
			"action": "CLICK",
			"throttle": 3000
		}
	]
}
]
`

**Comment by mengdg** [comment]
![image](https://user-images.githubusercontent.com/20390755/143211208-4d1dd37b-97cd-4702-b2fc-7bb1728e46a3.png)

**Comment by mengdg** [comment]
[
{
	"prob": 1,
	"activity": "com.soft.blued.ui.login_register.SignInActivity",
	"times": 10,
	"actions": [
		{
			"xpath":"//*[@resource-id='com.soft.blued:id/cev_mobile']//android.widget.EditText",
			"action": "CLICK",
			"text": "18518230989",
			"clearText": false,
			"throttle": 5000
		},
		{
			"xpath":"//*[@resource-id='com.soft.blued:id/cev_password']//android.widget.EditText",
			"action": "CLICK",
			"text": "123123",
			"clearText": false,
			"throttle": 5000
		},
		{
			"xpath": "//*[@resource-id='com.soft.blued:id/tv_login']",
			"action": "CLICK",
			"throttle": 5000
		}
	]
}
]

**Comment by mengdg** [comment]
appium inspect 获取的Activity和验证的xpath均没有问题，始终不执行自定义事件

**Comment by mengdg** [comment]
[Fastbot][2021-11-25 11:50:00.325] // phone info： samsung_SM-N9500_9
[Fastbot][2021-11-25 11:50:00.326] // runing fastbot
[Fastbot][2021-11-25 11:50:00.577] InputMethod ID: com.sec.android.inputmethod/.SamsungKeypad
[Fastbot][2021-11-25 11:50:00.578] InputMethod ID: com.android.adbkeyboard/.AdbIME
[Fastbot][2021-11-25 11:50:00.578] Find Keybaord: com.android.adbkeyboard/.AdbIME
[Fastbot][2021-11-25 11:50:00.589] // device serial number is ce061716e537962d017e
[Fastbot][2021-11-25 11:50:00.657] // device uuid is a950fc35-4d94-43bb-8262-92bf7591fc13
[Fastbot][2021-11-25 11:50:02.540] // init with reuse agent
[Fastbot][2021-11-25 11:50:02.554] fastbot native : library load!
[Fastbot][2021-11-25 11:50:02.564]

[Fastbot][2021-11-25 11:50:02.571] // the top activity is com.sec.android.app.launcher.activities.LauncherActivity, not testing app, need inject restart app
[Fastbot][2021-11-25 11:50:02.573] Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.soft.blued/.icon0;end
[Fastbot][2021-11-25 11:50:02.591] // the top activity is com.soft.blued.icon0, phone capture activity is com.sec.android.app.camera.Camera
[Fastbot][2021-11-25 11:50:02.593]     // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.soft.blued/.icon0 } in package com.soft.blued
[Fastbot][2021-11-25 11:50:02.614] // current activity is com.soft.blued.icon0
[Fastbot][2021-11-25 11:50:02.617] Sleeping for 2000 milliseconds
[Fastbot][2021-11-25 11:50:02.720] // the top activity is com.soft.blued.ui.welcome.WelcomeActivity, phone capture activity is com.sec.android.app.camera.Camera
[Fastbot][2021-11-25 11:50:02.722]     // Allowing start of Intent { cmp=com.soft.blued/.ui.welcome.WelcomeActivity } in package com.soft.blued
[Fastbot][2021-11-25 11:50:02.731]     // activityResuming(com.soft.blued)
[Fastbot][2021-11-25 11:50:04.625] // current activity is com.soft.blued.ui.welcome.WelcomeActivity
[Fastbot][2021-11-25 11:50:04.648] // Eventid: 3
[Fastbot][2021-11-25 11:50:04.687] action type: SCROLL_LEFT_RIGHT
[Fastbot][2021-11-25 11:50:04.690] rpc cost time: 34
[Fastbot][2021-11-25 11:50:04.703]  event time:63
[Fastbot][2021-11-25 11:50:04.706] :Sending rotation degree=0, persist=false
[Fastbot][2021-11-25 11:50:04.768] :Sending Touch (ACTION_DOWN): 0:(720.0,1480.0)
[Fastbot][2021-11-25 11:50:04.783] :Sending Touch (ACTION_MOVE): 0:(720.0,1480.0)
[Fastbot][2021-11-25 11:50:04.786] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:04.810] :Sending Touch (ACTION_MOVE): 0:(791.9,1480.0)
[Fastbot][2021-11-25 11:50:04.816] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:04.841] :Sending Touch (ACTION_MOVE): 0:(863.8,1480.0)
[Fastbot][2021-11-25 11:50:04.851] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:04.876] :Sending Touch (ACTION_MOVE): 0:(935.7,1480.0)
[Fastbot][2021-11-25 11:50:04.886] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:04.915] :Sending Touch (ACTION_MOVE): 0:(1007.6,1480.0)
[Fastbot][2021-11-25 11:50:04.925] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:04.950] :Sending Touch (ACTION_MOVE): 0:(1079.5,1480.0)
[Fastbot][2021-11-25 11:50:04.959] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:04.986] :Sending Touch (ACTION_MOVE): 0:(1151.4,1480.0)
[Fastbot][2021-11-25 11:50:04.997] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:05.022] :Sending Touch (ACTION_MOVE): 0:(1223.3,1480.0)
[Fastbot][2021-11-25 11:50:05.031] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:05.056] :Sending Touch (ACTION_MOVE): 0:(1295.2,1480.0)
[Fastbot][2021-11-25 11:50:05.063] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:05.091] :Sending Touch (ACTION_MOVE): 0:(1367.1,1480.0)
[Fastbot][2021-11-25 11:50:05.101] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:05.127] :Sending Touch (ACTION_UP): 0:(1439.0,1480.0)
[Fastbot][2021-11-25 11:50:05.140] Sleeping for 534 milliseconds
[Fastbot][2021-11-25 11:50:05.689] // Eventid: 27
[Fastbot][2021-11-25 11:50:05.697] action type: SCROLL_TOP_DOWN
[Fastbot][2021-11-25 11:50:05.704] rpc cost time: 9
[Fastbot][2021-11-25 11:50:05.713]  event time:32
[Fastbot][2021-11-25 11:50:05.716] :Sending rotation degree=0, persist=false
[Fastbot][2021-11-25 11:50:05.744] :Sending Touch (ACTION_DOWN): 0:(720.0,1480.0)
[Fastbot][2021-11-25 11:50:05.749] :Sending Touch (ACTION_MOVE): 0:(720.0,1480.0)
[Fastbot][2021-11-25 11:50:05.761] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:05.777] // the top activity is com.soft.blued.ui.login_register.SignInActivity, phone capture activity is com.sec.android.app.camera.Camera
[Fastbot][2021-11-25 11:50:05.778]     // Allowing start of Intent { cmp=com.soft.blued/.ui.login_register.SignInActivity } in package com.soft.blued
[Fastbot][2021-11-25 11:50:05.793]     // activityResuming(com.soft.blued)
[Fastbot][2021-11-25 11:50:05.797] // current activity is com.soft.blued.ui.login_register.SignInActivity
[Fastbot][2021-11-25 11:50:05.797]     // activityResuming(com.soft.blued)
[Fastbot][2021-11-25 11:50:05.799] :Sending Touch (ACTION_MOVE): 0:(720.0,1611.1)
[Fastbot][2021-11-25 11:50:05.814] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:05.839] :Sending Touch (ACTION_MOVE): 0:(720.0,1742.2)
[Fastbot][2021-11-25 11:50:05.841] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:05.865] :Sending Touch (ACTION_MOVE): 0:(720.0,1873.3)
[Fastbot][2021-11-25 11:50:05.867] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:05.890] :Sending Touch (ACTION_MOVE): 0:(720.0,2004.4)
[Fastbot][2021-11-25 11:50:05.892] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:05.915] :Sending Touch (ACTION_MOVE): 0:(720.0,2135.5)
[Fastbot][2021-11-25 11:50:05.917] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:05.939] :Sending Touch (ACTION_MOVE): 0:(720.0,2266.6)
[Fastbot][2021-11-25 11:50:05.942] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:05.966] :Sending Touch (ACTION_MOVE): 0:(720.0,2397.7)
[Fastbot][2021-11-25 11:50:05.973] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:05.995] :Sending Touch (ACTION_MOVE): 0:(720.0,2528.8)
[Fastbot][2021-11-25 11:50:05.997] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:06.020] :Sending Touch (ACTION_MOVE): 0:(720.0,2659.9)
[Fastbot][2021-11-25 11:50:06.023] Wait Event for 20 milliseconds
[Fastbot][2021-11-25 11:50:06.046] :Sending Touch (ACTION_UP): 0:(720.0,2791.0)
[Fastbot][2021-11-25 11:50:06.053] Sleeping for 575 milliseconds
[Fastbot][2021-11-25 11:50:06.641] // Eventid: 51
[Fastbot][2021-11-25 11:50:06.655] action type: CLICK
[Fastbot][2021-11-25 11:50:06.656] rpc cost time: 4
[Fastbot][2021-11-25 11:50:06.659]  event time:29
[Fastbot][2021-11-25 11:50:06.660] :Sending rotation degree=0, persist=false
[Fastbot][2021-11-25 11:50:06.675] :Sending Touch (ACTION_DOWN): 0:(979.0,2620.0)
[Fastbot][2021-11-25 11:50:06.678] :Sending Touch (ACTION_UP): 0:(979.0,2620.0)
[Fastbot][2021-11-25 11:50:06.685] Sleeping for 536 milliseconds
[Fastbot][2021-11-25 11:50:06.692] // the top activity is com.blued.android.core.ui.TerminalActivity, phone capture activity is com.sec.android.app.camera.Camera
[Fastbot][2021-11-25 11:50:06.693]     // Allowing start of Intent { cmp=com.soft.blued/com.blued.android.core.ui.TerminalActivity } in package com.soft.blued
[Fastbot][2021-11-25 11:50:07.223] // current activity is com.blued.android.core.ui.TerminalActivity
[Fastbot][2021-11-25 11:50:07.230] // Eventid: 55
[Fastbot][2021-11-25 11:50:07.237] action type: CLICK
[Fastbot][2021-11-25 11:50:07.238] rpc cost time: 4
[Fastbot][2021-11-25 11:50:07.241]  event time:17
[Fastbot][2021-11-25 11:50:07.242] :Sending rotation degree=0, persist=false
[Fastbot][2021-11-25 11:50:07.255] :Sending Touch (ACTION_DOWN): 0:(229.0,730.0)
[Fastbot][2021-11-25 11:50:07.258] :Sending Touch (ACTION_UP): 0:(229.0,730.0)
[Fastbot][2021-11-25 11:50:07.265] Sleeping for 560 milliseconds

**Comment by MRJC92** [comment]
我也遇到了相同的问题，这个有官方联系的微信群 之类的吗

**Comment by geron-cn** [comment]
可抓取下 logcat 看下自定义事件匹配过程

**Comment by sherryzheng0729** [comment]
请问启动 Fastbot的命令是什么，能使max.xpath.actions生效

**Comment by wan88888** [comment]
默认执行和按max.xpath.actions文件执行fastbot的命令都是adb -s R9PN30AK0MJ shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p vidma.video.editor.videomaker --agent reuseq --running-minutes 5 --throttle 500 -v -v -v吗？

**Comment by yanjinging** [comment]
请问各位有解决这个问题嘛，我也遇到了一样的问题，反复查了两天，实在想不到是哪里的问题
[
  {
    "prob": 1,
    "activity": "com.bjgoodwill.mobilemrb.ui.flash.FlashActivity",
    "actions": [
      {
        "xpath": "//*[@resource-id='com.bjgoodwill.beizhongmrb:id/btn_skip']",
        "index": 0,
        "action": "CLICK",
        "throttle": 3000
      }
    ]
  },
  {
    "prob": 1,
    "activity": "com.bjgoodwill.mobilemrb.ui.login.LoginActivity",
    "actions": [
      {
        "xpath": "//*[@resource-id='com.bjgoodwill.beizhongmrb:id/md_buttonDefaultNegative' and @text='以后再说']",
        "index": 2,
        "action": "CLICK",
        "throttle": 1000
      },
      {
        "xpath": "//*[@resource-id='com.bjgoodwill.beizhongmrb:id/et_phone']",
        "action": "INPUTTEXT",
        "text": "13333333333",
        "index": 0,
        "throttle": 2000
      },
      {
        "xpath": "//*[@resource-id='com.bjgoodwill.beizhongmrb:id/et_pswd']",
        "action": "INPUTTEXT",
        "text": "123456",
        "index": 0,
        "throttle": 2000
      },
      {
        "xpath": "//*[@resource-id='com.bjgoodwill.beizhongmrb:id/btn_login']",
        "action": "CLICK",
        "index": 3,
        "throttle": 2000
      }
    ]
  }
]

**Comment by yanjinging** [comment]
[Fastbot][2022-11-01 17:31:39.619] // current activity is com.bjgoodwill.mobilemrb.ui.flash.FlashActivity
[Fastbot][2022-11-01 17:31:39.620] Sleeping for 2000 milliseconds
[Fastbot][2022-11-01 17:31:42.835] // topcomp is null or newtree is null, accessibility maybe error, need do fuzz.
[Fastbot][2022-11-01 17:31:42.868] fastbot native : library load!
[Fastbot][2022-11-01 17:31:42.918]  event time:1296
[Fastbot][2022-11-01 17:31:42.918] :Sending rotation degree=0, persist=false
[Fastbot][2022-11-01 17:31:42.942] :Sending Touch (ACTION_DOWN): 0:(938.0,88.0)
[Fastbot][2022-11-01 17:31:42.966] Wait Event for 885 milliseconds
[Fastbot][2022-11-01 17:31:43.858] :Sending Touch (ACTION_UP): 0:(938.0,88.0)
[Fastbot][2022-11-01 17:31:43.874] :Sending Touch (ACTION_DOWN): 0:(452.0,892.0)
[Fastbot][2022-11-01 17:31:43.892] Wait Event for 783 milliseconds
[Fastbot][2022-11-01 17:31:44.679] :Sending Touch (ACTION_UP): 0:(452.0,892.0)
[Fastbot][2022-11-01 17:31:44.741] Shell command settings put global always_finish_activities 0 status was 0
[Fastbot][2022-11-01 17:31:44.748] :Sending Touch (ACTION_DOWN): 0:(198.0,1009.0)
[Fastbot][2022-11-01 17:31:44.752] Wait Event for 355 milliseconds
[Fastbot][2022-11-01 17:31:45.112] :Sending Touch (ACTION_UP): 0:(198.0,1009.0)
[Fastbot][2022-11-01 17:31:45.128] :Sending Touch (ACTION_DOWN): 0:(321.0,1039.0)
[Fastbot][2022-11-01 17:31:45.132] :Sending Touch (ACTION_UP): 0:(303.31113,1045.5026)
[Fastbot][2022-11-01 17:31:45.148] // Eventid: 22
[Fastbot][2022-11-01 17:31:45.172] action type: CLICK
[Fastbot][2022-11-01 17:31:45.173] rpc cost time: 19
[Fastbot][2022-11-01 17:31:45.179]  event time:38
[Fastbot][2022-11-01 17:31:45.180] :Sending rotation degree=0, persist=false
[Fastbot][2022-11-01 17:31:45.216] :Sending Touch (ACTION_DOWN): 0:(900.0,238.0)
[Fastbot][2022-11-01 17:31:45.222] :Sending Touch (ACTION_UP): 0:(900.0,238.0)
[Fastbot][2022-11-01 17:31:45.226] Sleeping for 4000 milliseconds
[Fastbot][2022-11-01 17:31:45.260] // the top activity is com.bjgoodwill.mobilemrb.ui.login.LoginActivity, phone capture activity is com.android.camera.CameraActivity
[Fastbot][2022-11-01 17:31:45.261]     // Allowing start of Intent { cmp=com.bjgoodwill.beizhongmrb/com.bjgoodwill.mobilemrb.ui.login.LoginActivity } in package com.bjgoodwill.beizhongmrb
[Fastbot][2022-11-01 17:31:45.290]     // activityResuming(com.bjgoodwill.beizhongmrb)
[Fastbot][2022-11-01 17:31:49.239] // current activity is com.bjgoodwill.mobilemrb.ui.login.LoginActivity
[Fastbot][2022-11-01 17:31:49.266] // Eventid: 26
[Fastbot][2022-11-01 17:31:49.275] action type: CLICK
[Fastbot][2022-11-01 17:31:49.276] rpc cost time: 4
[Fastbot][2022-11-01 17:31:49.287]  event time:34
[Fastbot][2022-11-01 17:31:49.289] :Sending rotation degree=0, persist=false
[Fastbot][2022-11-01 17:31:49.370] :Sending Touch (ACTION_DOWN): 0:(555.0,1300.0)
[Fastbot][2022-11-01 17:31:49.376] :Sending Touch (ACTION_UP): 0:(555.0,1300.0)
[Fastbot][2022-11-01 17:31:49.401] Sleeping for 2000 milliseconds
[Fastbot][2022-11-01 17:31:51.631] // topcomp is null or newtree is null, accessibility maybe error, need do fuzz.
[Fastbot][2022-11-01 17:31:51.642]  event time:235
[Fastbot][2022-11-01 17:31:51.644] :Sending rotation degree=0, persist=false
[Fastbot][2022-11-01 17:31:51.676] :Sending Key (ACTION_DOWN): 82    // KEYCODE_MENU
[Fastbot][2022-11-01 17:31:51.696] :Sending Key (ACTION_UP): 82    // KEYCODE_MENU
[Fastbot][2022-11-01 17:31:51.732] :Sending Key (ACTION_DOWN): 20    // KEYCODE_DPAD_DOWN
[Fastbot][2022-11-01 17:31:51.743] :Sending Key (ACTION_UP): 20    // KEYCODE_DPAD_DOWN
[Fastbot][2022-11-01 17:31:51.756] :Sending Touch (ACTION_DOWN): 0:(1046.0,94.0)
[Fastbot][2022-11-01 17:31:51.762] :Sending Touch (ACTION_MOVE): 0:(1045.6406,94.032036)
[Fastbot][2022-11-01 17:31:51.767] Wait Event for 20 milliseconds
[Fastbot][2022-11-01 17:31:51.791] :Sending Touch (ACTION_MOVE): 0:(1039.51,94.24926)
[Fastbot][2022-11-01 17:31:51.795] Wait Event for 20 milliseconds
[Fastbot][2022-11-01 17:31:51.820] :Sending Touch (ACTION_MOVE): 0:(1039.1896,94.68327)
[Fastbot][2022-11-01 17:31:51.824] Wait Event for 20 milliseconds
[Fastbot][2022-11-01 17:31:51.851] :Sending Touch (ACTION_MOVE): 0:(1032.7356,94.9478)
[Fastbot][2022-11-01 17:31:51.857] Wait Event for 20 milliseconds
[Fastbot][2022-11-01 17:31:51.882] :Sending Touch (ACTION_MOVE): 0:(1027.8082,95.018234)
[Fastbot][2022-11-01 17:31:51.891] Wait Event for 20 milliseconds
[Fastbot][2022-11-01 17:31:51.920] :Sending Touch (ACTION_MOVE): 0:(1026.1467,95.11943)
[Fastbot][2022-11-01 17:31:51.925] Wait Event for 20 milliseconds
[Fastbot][2022-11-01 17:31:51.950] :Sending Touch (ACTION_MOVE): 0:(1024.3497,95.44272)
[Fastbot][2022-11-01 17:31:51.956] Wait Event for 20 milliseconds
[Fastbot][2022-11-01 17:31:51.984] :Sending Touch (ACTION_MOVE): 0:(1019.96124,95.89199)
[Fastbot][2022-11-01 17:31:51.995] Wait Event for 20 milliseconds
[Fastbot][2022-11-01 17:31:52.026] :Sending Touch (ACTION_UP): 0:(1014.50494,96.295235)
[Fastbot][2022-11-01 17:31:52.049] :Sending Touch (ACTION_DOWN): 0:(872.0,937.0)
[Fastbot][2022-11-01 17:31:52.058] :Sending Touch (ACTION_MOVE): 0:(880.46375,935.18585)
[Fastbot][2022-11-01 17:31:52.067] Wait Event for 66 milliseconds
[Fastbot][2022-11-01 17:31:52.140] :Sending Touch (ACTION_UP): 0:(885.6672,930.8269)
[Fastbot][2022-11-01 17:31:52.155] :Sending Touch (ACTION_DOWN): 0:(295.0,694.0)
[Fastbot][2022-11-01 17:31:52.163] :Sending Touch (ACTION_MOVE): 0:(293.6608,690.2329)
[Fastbot][2022-11-01 17:31:52.169] Wait Event for 28 milliseconds
[Fastbot][2022-11-01 17:31:52.203] :Sending Touch (ACTION_MOVE): 0:(289.8719,689.63696)
[Fastbot][2022-11-01 17:31:52.212] Wait Event for 28 milliseconds
[Fastbot][2022-11-01 17:31:52.248] :Sending Touch (ACTION_MOVE): 0:(284.00076,688.005)
[Fastbot][2022-11-01 17:31:52.256] Wait Event for 28 milliseconds
[Fastbot][2022-11-01 17:31:52.292] :Sending Touch (ACTION_MOVE): 0:(283.40158,673.7339)
[Fastbot][2022-11-01 17:31:52.303] Wait Event for 28 milliseconds
[Fastbot][2022-11-01 17:31:52.338] :Sending Touch (ACTION_MOVE): 0:(274.484,667.8478)
[Fastbot][2022-11-01 17:31:52.346] Wait Event for 28 milliseconds
[Fastbot][2022-11-01 17:31:52.381] :Sending Touch (ACTION_UP): 0:(267.43353,662.5373)
[Fastbot][2022-11-01 17:31:52.412] :Sending Key (ACTION_DOWN): 91    // KEYCODE_MUTE
[Fastbot][2022-11-01 17:31:52.435] :Sending Key (ACTION_UP): 91    // KEYCODE_MUTE
[Fastbot][2022-11-01 17:31:52.487] :Sending Key (ACTION_DOWN): 187    // KEYCODE_APP_SWITCH
[Fastbot][2022-11-01 17:31:52.496] :Sending Key (ACTION_UP): 187    // KEYCODE_APP_SWITCH
[Fastbot][2022-11-01 17:31:52.534] Sleeping for 500 milliseconds
[Fastbot][2022-11-01 17:31:52.572] // the top activity is com.vivo.upslide.recents.RecentsActivity, phone capture activity is com.android.camera.CameraActivity
[Fastbot][2022-11-01 17:31:52.572]     // Rejecting start of Intent { cmp=com.vivo.upslide/.recents.RecentsActivity } in package com.vivo.upslide
[Fastbot][2022-11-01 17:31:53.042] :Sending Key (ACTION_DOWN): 3    // KEYCODE_HOME
[Fastbot][2022-11-01 17:31:53.062] :Sending Key (ACTION_UP): 3    // KEYCODE_HOME
[Fastbot][2022-11-01 17:31:53.103]     // activityResuming(com.bbk.launcher2)
[Fastbot][2022-11-01 17:31:53.104]     // Rejecting resume of package com.bbk.launcher2
[Fastbot][2022-11-01 17:31:53.143] :Sending rotation degree=1, persist=true
[Fastbot][2022-11-01 17:31:53.190] // Eventid: 89
[Fastbot][2022-11-01 17:31:53.195] action type: NOP

**Comment by zhangzhao4444** [comment]
下个版本fix
