### ISSUE TITLE
配置黑控件后，匹配到了黑控件，但是仍然点击了这个黑控件

### ISSUE THREAD

**Issue by HannahShen** [bytedance/Fastbot_Android#11]
执行命令：adb shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p dji.go.v5 --agent robot  --act-blacklist-file /sdcard/abl.strings  --running-minutes 30 --throttle 500 -v -v -v -v > fastbot4.log

问题：设置黑控件： //*[contains(@text,'对频')] ， line12-14 也匹配到了这个黑控件，然而在line39 仍触发了点击这个控件

手机：三星s10  android 9

错误日志：
1. 
2. [1609834717867] *** Get guitree ***
3. [1609834717873]     <?xml version="1.0" encoding="UTF-8"?>
4.             <node index="4" text="重新配对（对频）" resource-id="dji.go.v5:id/setting_ui_2_item_button_tv" class="android.widget.TextView" content-desc="" package="dji.go.v5" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" scroll-type="none" bounds="[1239,988][1535,1041]"/>
5.           </node>
6. [1609834717874] using nstep-q agent
7. [1609834717874] // Display Bounds: (112,0),(2280,1080)
8. [1609834717874] // Black Element : //*[contains(@resource-id,'fpv_map_shell_find_drone_btn')], Index : 0
9. [1609834717876] // matching 1 nodes, //*[contains(@resource-id,'fpv_map_shell_find_drone_btn')]
10. [1609834717876] // Black Element : //*[contains(@text,'更新')], Index : 0
11. [1609834717877] // No matching nodes
**12. [1609834717877] // Black Element : //*[contains(@text,'对频')], Index : 0
13. [1609834717879] // matching 1 nodes, //*[contains(@text,'对频')]
14. [1609834717879] // Black Element : //*[contains(@resource-id,'fmd_btn_flash_and_beep')], Index : 0**
15. [1609834717881] // No matching nodes
16. [1609834717882] // com.dji.component.fpv.FpvComponentActivity find 2 black widgets:
17. [1609834717882]   // black rect0: (1239,988),(1535,1041)
18. [1609834717882]   // black rect1: (1922,933),(2225,1059)
19. [1609834717883] select new action from unvisited
20. [1609834717883] new state visited : 11
21. [1609834717884] new action visited : 0
22. [1609834717884] get new reward
23. [1609834717884] alpha is : 0.6 default is : 0.2 moving alpha is 0.6
24. [1609834717885] action first visited, get reward 1.0
25. [1609834717885] update Q value
26. [1609834717885] // previous State and action polled
27. [1609834717885] // update change value
28. [1609834717886] get n step new reward
29. [1609834717886] 0step reward is 4.2
30. [1609834717886] 1step reward is 5.0
31. [1609834717887] 2step reward is 5.768
32. [1609834717887] 3step reward is 6.28
33. [1609834717887] 4step reward is 6.6896
34. [1609834717887] // got reward : 6.6896
35. [1609834717888] // got qvalue : 0.0
36. [1609834717888] Qt=0.0, Reward=6.6896, Qt+1=0.0, Qt'=4.01376
37. [1609834717888] *** Making decisions *** 
38. [1609834717889] New  state: g0s2@com.dji.component.fpv.FpvComponentActivity@-2101021068
39. **[1609834717889] New action: g0a72@CLICKWidget{hashCode=897765371, index=4, clazz='android.widget.TextView', resourceId='dji.go.v5:id/setting_ui_2_item_button_tv', operationTypeMask=6, scrollType=none, text='重新配对（对频）', contentDesc=''}[priority=24][throttle=200][][saturation=(0.0,1)][bounds=(1239,988,1535,1041)]**
40. [1609834717889] *** Inject event ***
41. [1609834717891] // fix point: (1387.0,974.875)
42. [1609834717891] :Sending Touch (ACTION_DOWN): 0:(1387.0,974.875)
43. [1609834717894] :Sending Touch (ACTION_UP): 0:(1387.0,974.875)
44. [1609834717899] Sleep for 0 ms
45. [1609834717900] Sleep for 700 ms
46. [1609834718605] Sleep for 0 ms
47. [1609834722042] Exception for get action resouece: g0a164@CLICKWidget{hashCode=-1685199248, index=0, clazz='android.widget.TextView', resourceId='dji.go.v5:id/tv_second', operationTypeMask=22, scrollType=none, text='点击飞机上的对频', contentDesc=''}[priority=0][throttle=200][, UNVISITED][saturation=(0.0,1)][bounds=(828,464,1563,510)]
48. [1609834722045] Exception for get action resouece: g0a165@LONG_CLICKWidget{hashCode=-1685199248, index=0, clazz='android.widget.TextView', resourceId='dji.go.v5:id/tv_second', operationTypeMask=22, scrollType=none, text='点击飞机上的对频', contentDesc=''}[priority=0][throttle=200][, UNVISITED][saturation=(0.0,1)][bounds=(828,464,1563,510)]
49. [1609834722046] Exception for get action resouece: g0a166@CLICKWidget{hashCode=-178375035, index=1, clazz='android.widget.TextView', resourceId='dji.go.v5:id/tv_positive', operationTypeMask=6, scrollType=none, text='取消（59）', contentDesc=''}[priority=0][throttle=200][, UNVISITED][saturation=(0.0,1)][bounds=(828,574,1563,711)]
50. [1609834722047] Exception for get action resouece: g0a167@BACKg0s7@com.dji.component.fpv.FpvComponentActivity@60073284[priority=0][throttle=200][, UNVISITED]
51. [1609834722048] Exception for get action class: g0a167@BACKg0s7@com.dji.component.fpv.FpvComponentActivity@60073284[priority=0][throttle=200][, UNVISITED]

完整日志：
[fastbot4.log](https://github.com/bytedance/Fastbot_Android/files/5768932/fastbot4.log)

**Comment by mengbin890815** [comment]
我也遇到了这个问题，设置了黑控件，运行过程中还是会click

**Comment by zhangzhao4444** [comment]
看Log是黑控件有效的
 text='重新配对（对频）', contentDesc=''}[priority=24][throttle=200][][saturation=(0.0,1)][bounds=(1239,988,1535,1041)]
实际操作fix point: (1387.0,974.875)
将坐标上移出黑控件区域；  看看是否有其他什么问题？

另外建议也加上二代黑控件max.tree.pruning 直接从build tree 层面裁剪

**Comment by HannahShen** [comment]
已解决， 黑控件配置的问题， 我选取的黑控件不全，父节点区域也会触发不希望的操作
也增加了树剪枝屏蔽，未出现该问题
