### ISSUE TITLE
自动化测试没有报错，没有死机，UI没有反应。但是手动可以继续点击

### ISSUE THREAD

**Issue by fengfeng-hight** [bytedance/Fastbot_Android#110]
以下是分别测试两次 ，分别的信息
1. 
[log_event.txt](https://github.com/bytedance/Fastbot_Android/files/7599662/log_event.txt)
![step-9--g0a43-1637669940241](https://user-images.githubusercontent.com/58496922/143365427-130c303e-a955-47f2-81fe-473c1913b944.png)
 
![step-9--g0a43-1637669940241](https://user-images.githubusercontent.com/58496922/143365443-e4e745e4-8948-44a9-a8b1-be569add34ca.png)

2.
[log_event.txt](https://github.com/bytedance/Fastbot_Android/files/7599671/log_event.txt)
 
![step-4--g0a33-1637756760332](https://user-images.githubusercontent.com/58496922/143365617-74d9912e-df5f-4ac6-80c5-163e741290a0.png)
![step-3--g0a33-1637756759697](https://user-images.githubusercontent.com/58496922/143365629-0700e669-27c7-4e6b-a007-61726c854a98.png)

**Comment by fengfeng-hight** [comment]
这是最后的几张图片

**Comment by geron-cn** [comment]
从现有资料上看起来是没有问题的，
可以抓一下 logcat，贴一下， 看下解析出来的页面是什么样子，
