### ISSUE TITLE
max.xpath.actions中的步骤，每次启动都会执行么？我看log，并没有执行呢？脚本没问题。如果设置了100次，会在进入那个activity的时候，先执行100次？

### ISSUE THREAD

**Issue by qqtester** [bytedance/Fastbot_Android#114]

**Comment by pingchaodeng** [comment]
我也是设置了步骤，但是并没有执行

**Comment by zhangzhao4444** [comment]
需要提供xpath.actions配置，具体问题分析下

**Comment by github653224** [comment]
我的也是， max.path.actions 根本没有按照这个文件去执行，是不是有bug我看作者也不维护

**Comment by qqtester** [comment]
> 我的也是， max.path.actions 根本没有按照这个文件去执行，是不是有bug我看作者也不维护

好像很久没看到工具更新了～！

**Comment by zhangzhao4444** [comment]
https://github.com/bytedance/Fastbot_Android/issues/108  类似问题。 这种问题大多是action配置问题，需要提供配置文件看下，好排查问题
