### ISSUE TITLE
运行后报Error: Count is not a number

### ISSUE THREAD

**Issue by seminchen** [bytedance/Fastbot_Android#115]
adb -s UY1 shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec appr ocess /system/bin com.android.commands.monkey.Monkey -p com.v.test --agent robot --running-minutes 30 --throttle 500 -v -v --bugreport

[Fastbot][2021-12-17 19:18:11.932]  @Version: 2.2.01.1101.2108-git
** Error: Count is not a number
usage: monkey [-p ALLOWED_PACKAGE [-p ALLOWED_PACKAGE] ...]
              [-c MAIN_CATEGORY [-c MAIN_CATEGORY] ...]
              [--ignore-crashes] [--ignore-timeouts]
              [--ignore-security-exceptions]
              [--agent [AGENT_TYPE(walk,stat)]]
              [--running-minutes MINUTES
              [--monitor-native-crashes] [--ignore-native-crashes]
              [--kill-process-after-error] [--hprof]
              [--pct-touch PERCENT] [--pct-motion PERCENT]
              [--pct-trackball PERCENT] [--pct-syskeys PERCENT]
              [--pct-nav PERCENT] [--pct-majornav PERCENT]
              [--pct-appswitch PERCENT] [--pct-flip PERCENT]
              [--pct-anyevent PERCENT] [--pct-pinchzoom PERCENT]
              [--pct-permission PERCENT]
              [--pkg-blacklist-file PACKAGE_BLACKLIST_FILE]
              [--pkg-whitelist-file PACKAGE_WHITELIST_FILE]
              [--wait-dbg] [--dbg-no-events]
              [--setup scriptfile] [-f scriptfile [-f scriptfile] ...]
              [--port port]
              [-s SEED] [-v [-v] ...]
              [--throttle MILLISEC] [--randomize-throttle]
              [--profile-wait MILLISEC]
              [--device-sleep-time MILLISEC]
              [--randomize-script]
              [--script-log]
              [--bugreport]
              [--periodic-bugreport]
              [--permission-target-system]
              COUNT

**Comment by geron-cn** [comment]
启动命令参数错误， 请再检查下启动参数， 
另外你这个应该是旧版本， 最新版本需要push的包和启动参数都有变化 。

**Comment by zhangzhao4444** [comment]
这个是shell命令输入有错误，可以手动去掉命令间的空格，再手动加上。 猜测是copy时被默认增加了特殊字符
