### ISSUE TITLE
初次运行fastbot，报错空指针异常，手动启动所测试的软件，再运行fastbot，可以成功运行，之后的运行也不需要再手动启动了

### ISSUE THREAD

**Issue by leavewave** [bytedance/Fastbot_Android#116]
机型：oppo find x2 8G+256G 骁龙865 八核
安卓版本：11 

![e48b87f6bd4406d1b36801ac4c9c6b1](https://user-images.githubusercontent.com/41049484/146921387-cb3af9e1-e821-420a-b357-541d8ce531ee.png)

**Comment by zhangzhao4444** [comment]
帮提供下fastbot运行时的版本号，在log最开头 version
