### ISSUE TITLE
无法执行自定义事件

### ISSUE THREAD

**Issue by pingchaodeng** [bytedance/Fastbot_Android#117]
[
{
    "prob": 1,
    "activity":"com.spero.vision.vsnapp/.MainActivity",
    "times": 1,
    "actions": [
        {
            "xpath":"//*[@resource-id='com.spero.vision.vsnapp:id/home_search_layout']",
            "throttle": 5000,
            "action": "CLICK",
            "throttle": 1000
        },
        {
            "xpath":"//*[@resource-id='com.spero.vision.vsnapp:id/search_edit_text']",
            "action": "CLICK",
            "text":"茅台",
            "clearText":false,
            "throttle": 1000
        },
        {
            "xpath":"//*[@resource-id='com.spero.vision.vsnapp:id/tv_state']",
            "action": "CLICK",
            "throttle": 1000
        },
        {
            "xpath":"//*[@resource-id='com.spero.vision.vsnapp:id/icon_phone_login']",
            "action": "CLICK",
            "throttle": 1000
        }
    ]
}
]

**Comment by pingchaodeng** [comment]
json.cn里检查过了，max.xpath.actions文件push到sdcard，ADBKeyBoard.apk也安装并设为默认输入法。执行的时候没有按照设定的事件执行

**Comment by pingchaodeng** [comment]
[运行log.txt](https://github.com/bytedance/Fastbot_Android/files/7779042/log.txt)

adb logcat | findstr fastbot

12-27 15:43:48.128 30653 30653 E linker  : library "/storage/emulated/0/oat/arm64/fastbot-thirdpart.odex" ("/storage/emulated/0/oat/arm64/fastbot-thirdpart.odex") needed or dlopened by "/apex/com.android.runtime/lib64/libart.so" is not accessible for the namespace: [name="(default)", ld_library_paths="", default_library_paths="/system/lib64:/system/product/lib64", permitted_paths="/system/lib64/drm:/system/lib64/extractors:/system/lib64/hw:/system/product/lib64:/system/framework:/system/app:/system/priv-app:/vendor/framework:/vendor/app:/vendor/priv-app:/system/vendor/framework:/system/vendor/app:/system/vendor/priv-app:/odm/framework:/odm/app:/odm/priv-app:/oem/app:/system/product/framework:/system/product/app:/system/product/priv-app:/data:/mnt/expand:/apex/com.android.runtime/lib64/bionic:/system/lib64/bootstrap"]
12-27 15:43:51.240 30653 30653 I [Fastbot]: // runing fastbot
12-27 15:43:54.600 30653 30653 I [Fastbot]: fastbot native : library load!
12-27 15:43:54.608 30653 30653 I [Fastbot]: begin load model: /sdcard/fastbot_com.spero.vision.vsnapp.fbm
12-27 15:44:54.829 30653 30653 I [Fastbot]: save model to path: /sdcard/fastbot_com.spero.vision.vsnapp.fbm

**Comment by github653224** [comment]
我也遇到这个文件设置好xpath后 并没有按照这个脚本执行

**Comment by zhangzhao4444** [comment]
"xpath":"//[@resource-id='com.spero.vision.vsnapp:id/home_search_layout']",
少了*，应该是

**Comment by zhangzhao4444** [comment]
"xpath":"//*[@resource-id='com.spero.vision.vsnapp:id/home_search_layout']",

**Comment by pingchaodeng** [comment]
> "xpath":"//*[@resource-id='com.spero.vision.vsnapp:id/home_search_layout']",

加上*也未执行自定义事件

**Comment by mmkxyu** [comment]
我开始也是不跑，然后最后解决了可以正常跑了，有2个原因：
1、activitity写错了，你这"activity":"com.spero.vision.vsnapp/.MainActivity",多了一个/，应该是"activity":"com.spero.vision.vsnapp.MainActivity"
2、ADBKeyBoard.apk安装并设为默认输入法，但是密码键盘用的还是默认的安全键盘，我去手机的设置-系统-输入法，关闭了安全输入
就好了，目前可以正常执行自定义事件了

**Comment by mimajiushi** [comment]
> 我开始也是不跑，然后最后解决了可以正常跑了，有2个原因： 1、activitity写错了，你这"activity":"com.spero.vision.vsnapp/.MainActivity",多了一个/，应该是"activity":"com.spero.vision.vsnapp.MainActivity" 2、ADBKeyBoard.apk安装并设为默认输入法，但是密码键盘用的还是默认的安全键盘，我去手机的设置-系统-输入法，关闭了安全输入 就好了，目前可以正常执行自定义事件了

没用阿，我看开发者也标记为bug了，你用的是哪个分支的版本？

**Comment by pingchaodeng** [comment]
> 我开始也是不跑，然后最后解决了可以正常跑了，有2个原因： 1、activitity写错了，你这"activity":"com.spero.vision.vsnapp/.MainActivity",多了一个/，应该是"activity":"com.spero.vision.vsnapp.MainActivity" 2、ADBKeyBoard.apk安装并设为默认输入法，但是密码键盘用的还是默认的安全键盘，我去手机的设置-系统-输入法，关闭了安全输入 就好了，目前可以正常执行自定义事件了

斜杠的原因，去掉后可以正常执行。但又引发了新的问题
一个页面需要多次输入内容的时候，每次输入后都会关闭这个页面。
比如登录页面，输入账号后，页面关闭，再次自动打开，输入密码，这时候账号输入框已经被清空了

**Comment by zhangzhao4444** [comment]
> > 我开始也是不跑，然后最后解决了可以正常跑了，有2个原因： 1、activitity写错了，你这"activity":"com.spero.vision.vsnapp/.MainActivity",多了一个/，应该是"activity":"com.spero.vision.vsnapp.MainActivity" 2、ADBKeyBoard.apk安装并设为默认输入法，但是密码键盘用的还是默认的安全键盘，我去手机的设置-系统-输入法，关闭了安全输入 就好了，目前可以正常执行自定义事件了
> 
> 斜杠的原因，去掉后可以正常执行。但又引发了新的问题 一个页面需要多次输入内容的时候，每次输入后都会关闭这个页面。 比如登录页面，输入账号后，页面关闭，再次自动打开，输入密码，这时候账号输入框已经被清空了

你这个情况应该是未执行的action配置有问题，执行序列中断了
