### ISSUE TITLE
报错java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission

### ISSUE THREAD

**Issue by ShenJiaojiao** [bytedance/Fastbot_Android#119]
红米

localhost:Fastbot_Android shenjiaojiao$ adb -s ea7a68b40406 shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.chehejia.oc.m01 --agent reuseq --running-minutes 100 --throttle 100 -v -v
▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄ 
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░▌ ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀▀▀  ▀▀▀▀█░█▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀█░▌ ▀▀▀▀█░█▀▀▀▀ 
▐░▌          ▐░▌       ▐░▌▐░▌               ▐░▌     ▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌     
▐░█▄▄▄▄▄▄▄▄▄ ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄▄▄      ▐░▌     ▐░█▄▄▄▄▄▄▄█░▌▐░▌       ▐░▌     ▐░▌     
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌     ▐░▌     ▐░░░░░░░░░░▌ ▐░▌       ▐░▌     ▐░▌     
▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌ ▀▀▀▀▀▀▀▀▀█░▌     ▐░▌     ▐░█▀▀▀▀▀▀▀█░▌▐░▌       ▐░▌     ▐░▌     
▐░▌          ▐░▌       ▐░▌          ▐░▌     ▐░▌     ▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌     
▐░▌          ▐░▌       ▐░▌ ▄▄▄▄▄▄▄▄▄█░▌     ▐░▌     ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄█░▌     ▐░▌     
▐░▌          ▐░▌       ▐░▌▐░░░░░░░░░░░▌     ▐░▌     ▐░░░░░░░░░░▌ ▐░░░░░░░░░░░▌     ▐░▌     
 ▀            ▀         ▀  ▀▀▀▀▀▀▀▀▀▀▀       ▀       ▀▀▀▀▀▀▀▀▀▀   ▀▀▀▀▀▀▀▀▀▀▀       ▀
[Fastbot][2021-12-31 13:50:45.548]  @Version: 2.2.01.1002.2151-git
[Fastbot][2021-12-31 13:50:45.574] // Monkey: seed=1641194618170 count=1000

[Fastbot][2021-12-31 13:50:45.575] // AllowPackage: com.chehejia.oc.m01
[Fastbot][2021-12-31 13:50:45.575] // IncludeCategory: android.intent.category.LAUNCHER
[Fastbot][2021-12-31 13:50:45.576] // IncludeCategory: android.intent.category.MONKEY
[Fastbot][2021-12-31 13:50:45.591] // Selecting main activities from category android.intent.category.LAUNCHER
[Fastbot][2021-12-31 13:50:45.592] //   - NOT USING main activity com.android.browser.launch.SplashActivity (from package com.android.browser)
[Fastbot][2021-12-31 13:50:45.592] //   - NOT USING main activity com.android.calendar.homepage.AllInOneActivity (from package com.android.calendar)
[Fastbot][2021-12-31 13:50:45.592] //   - NOT USING main activity com.android.camera.Camera (from package com.android.camera)
[Fastbot][2021-12-31 13:50:45.592] //   - NOT USING main activity com.android.contacts.activities.PeopleActivity (from package com.android.contacts)
[Fastbot][2021-12-31 13:50:45.593] //   - NOT USING main activity com.android.contacts.activities.TwelveKeyDialer (from package com.android.contacts)
[Fastbot][2021-12-31 13:50:45.593] //   - NOT USING main activity com.android.deskclock.DeskClockTabActivity (from package com.android.deskclock)
[Fastbot][2021-12-31 13:50:45.593] //   - NOT USING main activity com.android.fileexplorer.FileExplorerTabActivity (from package com.android.fileexplorer)
[Fastbot][2021-12-31 13:50:45.593] //   - NOT USING main activity com.android.mms.ui.MmsTabActivity (from package com.android.mms)
[Fastbot][2021-12-31 13:50:45.594] //   - NOT USING main activity com.android.settings.MainSettings (from package com.android.settings)
[Fastbot][2021-12-31 13:50:45.594] //   - NOT USING main activity com.android.soundrecorder.SoundRecorder (from package com.android.soundrecorder)
[Fastbot][2021-12-31 13:50:45.594] //   - NOT USING main activity com.android.thememanager.ThemeResourceTabActivity (from package com.android.thememanager)
[Fastbot][2021-12-31 13:50:45.594] //   - NOT USING main activity com.xiaomi.jr.app.MiFinanceActivity (from package com.mipay.wallet)
[Fastbot][2021-12-31 13:50:45.595] //   - NOT USING main activity com.miui.gallery.activity.HomePageActivity (from package com.miui.gallery)
[Fastbot][2021-12-31 13:50:45.595] //   - NOT USING main activity com.miui.miservice.main.MainActivity (from package com.miui.miservice)
[Fastbot][2021-12-31 13:50:45.595] //   - NOT USING main activity com.xiaomi.market.ui.MarketTabActivity (from package com.xiaomi.market)
[Fastbot][2021-12-31 13:50:45.595] //   - NOT USING main activity com.miui.calculator.cal.CalculatorActivity (from package com.miui.calculator)
[Fastbot][2021-12-31 13:50:45.595] //   - NOT USING main activity com.miui.notes.ui.NotesListActivity (from package com.miui.notes)
[Fastbot][2021-12-31 13:50:45.596] //   - NOT USING main activity com.miui.weather2.ActivityWeatherMain (from package com.miui.weather2)
[Fastbot][2021-12-31 13:50:45.596] //   - NOT USING main activity com.e4a.runtime.android.StartActivity (from package com.resource.download)
[Fastbot][2021-12-31 13:50:45.596] //   - NOT USING main activity com.e4a.runtime.android.StartActivity (from package com.somagnet)
[Fastbot][2021-12-31 13:50:45.596] //   - NOT USING main activity com.xiaomi.jr.app.MiFinanceActivity (from package com.xiaomi.jr)
[Fastbot][2021-12-31 13:50:45.597] //   - NOT USING main activity com.xiaomi.scanner.app.ScanActivity (from package com.xiaomi.scanner)
[Fastbot][2021-12-31 13:50:45.597] //   - NOT USING main activity com.android.providers.downloads.ui.DownloadList (from package com.android.providers.downloads.ui)
[Fastbot][2021-12-31 13:50:45.597] //   - NOT USING main activity com.android.stk.StkMain (from package com.android.stk)
[Fastbot][2021-12-31 13:50:45.597] //   - NOT USING main activity fm.qingting.qtradio.WelcomeActivity (from package com.miui.fm)
[Fastbot][2021-12-31 13:50:45.597] //   - NOT USING main activity com.miui.player.ui.MusicBrowserActivity (from package com.miui.player)
[Fastbot][2021-12-31 13:50:45.598] //   - NOT USING main activity com.miui.securityscan.MainActivity (from package com.miui.securitycenter)
[Fastbot][2021-12-31 13:50:45.598] //   - NOT USING main activity com.miui.video.Launcher1 (from package com.miui.video)
[Fastbot][2021-12-31 13:50:45.598] //   - NOT USING main activity com.xiaomi.voiceassistant.MainActivity (from package com.miui.voiceassist)
[Fastbot][2021-12-31 13:50:45.598] //   - NOT USING main activity tv.douyu.view.activity.launcher.DYSplashLauncherActivity (from package air.tv.douyu.android)
[Fastbot][2021-12-31 13:50:45.599] //   - NOT USING main activity cn.wps.moffice.documentmanager.PreStartActivity (from package cn.wps.moffice_eng)
[Fastbot][2021-12-31 13:50:45.599] //   - NOT USING main activity com.UCMobile.main.UCMobile (from package com.UCMobile)
[Fastbot][2021-12-31 13:50:45.599] //   - NOT USING main activity com.aaron.testmodel.MainActivity (from package com.aaron.testmodel)
[Fastbot][2021-12-31 13:50:45.599] //   - NOT USING main activity com.wps.multiwindow.main.HomeActivity (from package com.android.email)
[Fastbot][2021-12-31 13:50:45.600] //   - NOT USING main activity com.autonavi.map.activity.SplashActivity (from package com.autonavi.minimap)
[Fastbot][2021-12-31 13:50:45.600] //   - NOT USING main activity com.baidu.searchbox.SplashActivity (from package com.baidu.searchbox)
[Fastbot][2021-12-31 13:50:45.600] //   + Using main activity com.chehejia.oc.m01.business.home.LoginActivity (from package com.chehejia.oc.m01)
[Fastbot][2021-12-31 13:50:45.600] //   + Using main activity leakcanary.internal.activity.LeakLauncherActivity (from package com.chehejia.oc.m01)
[Fastbot][2021-12-31 13:50:45.601] //   - NOT USING main activity com.cnvcs.App (from package com.cnvcs.go)
[Fastbot][2021-12-31 13:50:45.601] //   - NOT USING main activity com.douban.frodo.activity.SplashActivity (from package com.douban.frodo)
[Fastbot][2021-12-31 13:50:45.601] //   - NOT USING main activity com.dragon.read.pages.splash.SplashActivity (from package com.dragon.read)
[Fastbot][2021-12-31 13:50:45.601] //   - NOT USING main activity com.xiaomi.mitv.phone.remotecontroller.HoriWidgetMainActivityV2 (from package com.duokan.phone.remotecontroller)
[Fastbot][2021-12-31 13:50:45.602] //   - NOT USING main activity com.duokan.reader.DkReaderActivity (from package com.duokan.reader)
[Fastbot][2021-12-31 13:50:45.602] //   - NOT USING main activity com.duowan.kiwi.simpleactivity.SplashActivity (from package com.duowan.kiwi)
[Fastbot][2021-12-31 13:50:45.602] //   - NOT USING main activity com.eastmoney.android.berlin.activity.MainActivity (from package com.eastmoney.android.berlin)
[Fastbot][2021-12-31 13:50:45.602] //   - NOT USING main activity com.eg.android.AlipayGphone.AlipayLogin (from package com.eg.android.AlipayGphone)
[Fastbot][2021-12-31 13:50:45.602] //   - NOT USING main activity com.example.aaron.androidtest.MainActivity (from package com.example.aaron.androidtest)
[Fastbot][2021-12-31 13:50:45.603] //   - NOT USING main activity com.feng.work.MainActivity (from package com.feng.work)
[Fastbot][2021-12-31 13:50:45.603] //   - NOT USING main activity com.lixiang.fed.liutopia.view.SplashActivity (from package com.lixiang.fed.liutopia)
[Fastbot][2021-12-31 13:50:45.603] //   - NOT USING main activity com.lixiang.fed.track.android.SplashActivity (from package com.lixiang.fed.track.android)
[Fastbot][2021-12-31 13:50:45.603] //   - NOT USING main activity com.mi.health.home.HomeActivity (from package com.mi.health)
[Fastbot][2021-12-31 13:50:45.604] //   - NOT USING main activity com.miui.compass.CompassActivity (from package com.miui.compass)
[Fastbot][2021-12-31 13:50:45.604] //   - NOT USING main activity com.miui.huanji.MainActivity (from package com.miui.huanji)
[Fastbot][2021-12-31 13:50:45.604] //   - NOT USING main activity com.miui.screenrecorder.activity.ScreenRecorderHomeActivity (from package com.miui.screenrecorder)
[Fastbot][2021-12-31 13:50:45.604] //   - NOT USING main activity com.miui.virtualsim.ui.MainActivity (from package com.miui.virtualsim)
[Fastbot][2021-12-31 13:50:45.605] //   - NOT USING main activity com.netease.gl.ui.activity.welcome.WelcomeInitActivity (from package com.netease.gl)
[Fastbot][2021-12-31 13:50:45.605] //   - NOT USING main activity com.netease.mhxyhtb.Launcher (from package com.netease.mhxyhtb)
[Fastbot][2021-12-31 13:50:45.605] //   - NOT USING main activity com.rocketbtdownload.rg_qdl (from package com.rocketbtdownload)
[Fastbot][2021-12-31 13:50:45.605] //   - NOT USING main activity com.sangfor.vpn.client.phone.WelcomeActivity (from package com.sangfor.vpn.client.phone)
[Fastbot][2021-12-31 13:50:45.606] //   - NOT USING main activity com.sina.weibo.SplashActivity (from package com.sina.weibo)
[Fastbot][2021-12-31 13:50:45.606] //   - NOT USING main activity com.ss.android.article.news.activity.MainActivity (from package com.ss.android.article.news)
[Fastbot][2021-12-31 13:50:45.606] //   - NOT USING main activity com.taobao.tao.welcome.Welcome (from package com.taobao.taobao)
[Fastbot][2021-12-31 13:50:45.606] //   - NOT USING main activity com.tencent.map.WelcomeActivity (from package com.tencent.map)
[Fastbot][2021-12-31 13:50:45.606] //   - NOT USING main activity com.tencent.mtt.SplashActivity (from package com.tencent.mtt)
[Fastbot][2021-12-31 13:50:45.607] //   - NOT USING main activity com.xiaomi.gamecenter.ui.MainTabActivity (from package com.xiaomi.gamecenter)
[Fastbot][2021-12-31 13:50:45.607] //   - NOT USING main activity com.xiaomi.shop.activity.MainTabActivity (from package com.xiaomi.shop)
[Fastbot][2021-12-31 13:50:45.607] //   - NOT USING main activity com.xiaomi.smarthome.SmartHomeMainActivity (from package com.xiaomi.smarthome)
[Fastbot][2021-12-31 13:50:45.607] //   - NOT USING main activity com.xiaomi.mi.launch.LaunchActivity (from package com.xiaomi.vipaccount)
[Fastbot][2021-12-31 13:50:45.608] //   - NOT USING main activity com.xiaomi.youpin.activity.SplashActivity (from package com.xiaomi.youpin)
[Fastbot][2021-12-31 13:50:45.608] //   - NOT USING main activity com.xunmeng.pinduoduo.ui.activity.MainFrameActivity (from package com.xunmeng.pinduoduo)
[Fastbot][2021-12-31 13:50:45.608] //   - NOT USING main activity com.zhihu.android.app.ui.activity.LauncherActivity (from package com.zhihu.android)
[Fastbot][2021-12-31 13:50:45.608] //   - NOT USING main activity io.github.ryanhoo.music.ui.main.MainActivity (from package io.github.ryanhoo.music)
[Fastbot][2021-12-31 13:50:45.609] //   - NOT USING main activity me.sam.czxing.MainActivity (from package me.devilsen.czxing)
[Fastbot][2021-12-31 13:50:45.609] //   - NOT USING main activity tv.danmaku.bili.MainActivityV2 (from package tv.danmaku.bili)
[Fastbot][2021-12-31 13:50:45.612] // Selecting main activities from category android.intent.category.MONKEY
[Fastbot][2021-12-31 13:50:45.612] //   - NOT USING main activity com.android.quicksearchbox.SearchActivity (from package com.android.quicksearchbox)
[Fastbot][2021-12-31 13:50:45.613] //   - NOT USING main activity com.miui.cloudbackup.ui.CloudBackupDetailActivity (from package com.miui.cloudbackup)
[Fastbot][2021-12-31 13:50:45.613] //   - NOT USING main activity com.miui.cloudservice.ui.MiCloudMainActivity (from package com.miui.cloudservice)
[Fastbot][2021-12-31 13:50:45.613] //   - NOT USING main activity com.miui.home.launcher.Launcher (from package com.miui.home)
[Fastbot][2021-12-31 13:50:45.614] //   - NOT USING main activity miui.notification.management.activity.NotificationAppListActivity (from package com.miui.notification)
[Fastbot][2021-12-31 13:50:45.614] //   - NOT USING main activity com.xiaomi.account.ui.AccountSettingsActivity (from package com.xiaomi.account)
[Fastbot][2021-12-31 13:50:45.614] //   - NOT USING main activity com.xiaomi.payment.MiliCenterEntryActivity (from package com.xiaomi.payment)
[Fastbot][2021-12-31 13:50:45.614] //   - NOT USING main activity com.xiaomi.drivemode.UserGuideActivity (from package com.xiaomi.drivemode)
[Fastbot][2021-12-31 13:50:45.615] //   - NOT USING main activity com.miui.accessibility.asr.component.message.MessageActivity (from package com.miui.accessibility)
[Fastbot][2021-12-31 13:50:45.615] //   - NOT USING main activity com.miui.micloudsync.MonkeyActivity (from package com.miui.micloudsync)
[Fastbot][2021-12-31 13:50:45.615] //   - NOT USING main activity com.miui.personalassistant.setting.PASettingActivity (from package com.miui.personalassistant)
[Fastbot][2021-12-31 13:50:45.615] //   - NOT USING main activity com.wps.multiwindow.main.HomeActivity (from package com.android.email)
[Fastbot][2021-12-31 13:50:45.616] //   - NOT USING main activity com.miui.virtualsim.monkeyentry.MonkeyActivity (from package com.miui.virtualsim)
[Fastbot][2021-12-31 13:50:45.616] //   - NOT USING main activity com.xiaomi.drivemode.DriveModeSettingsActivity (from package com.xiaomi.drivemode)
[Fastbot][2021-12-31 13:50:45.616] //   - NOT USING main activity com.xiaomi.drivemode.DriveModeAnimActivity (from package com.xiaomi.drivemode)
[Fastbot][2021-12-31 13:50:45.616] //   - NOT USING main activity com.xiaomi.drivemode.MiuiLabDriveModeActivity (from package com.xiaomi.drivemode)
[Fastbot][2021-12-31 13:50:45.617] //   - NOT USING main activity com.xiaomi.mi.launch.LaunchActivity (from package com.xiaomi.vipaccount)
[Fastbot][2021-12-31 13:50:48.618] // phone info： Xiaomi_M2003J15SC_10
[Fastbot][2021-12-31 13:50:48.619] // runing fastbot
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at java.io.FileReader.<init>(FileReader.java:58)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
	at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
	at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
	at android.content.res.Resources.<init>(Resources.java:285)
	at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
	at android.content.res.Resources.getSystem(Resources.java:206)
	at android.app.ActivityManager.isHighEndGfx(ActivityManager.java:936)
	at android.app.ActivityThread.systemMain(ActivityThread.java:7354)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.commands.monkey.f.b.ap(SourceFile:42)
	at com.android.commands.monkey.framework.AndroidDevice.a(SourceFile:108)
	at com.android.commands.monkey.Monkey.a(SourceFile:790)
	at com.android.commands.monkey.Monkey.main(SourceFile:454)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 21 more
[Fastbot][2021-12-31 13:50:48.688] InputMethod ID: com.baidu.input_mi/.ImeService
[Fastbot][2021-12-31 13:50:48.690] InputMethod ID: com.iflytek.inputmethod.miui/.FlyIME
[Fastbot][2021-12-31 13:50:48.690] InputMethod ID: com.sohu.inputmethod.sogou.xiaomi/.SogouIME
[Fastbot][2021-12-31 13:50:48.696] // device serial number is ea7a68b40406
[Fastbot][2021-12-31 13:50:48.732] // device uuid is 0e13c3fb-8362-4d52-b06d-670271ae6d56
[Fastbot][2021-12-31 13:50:52.320] // init with reuse agent
[Fastbot][2021-12-31 13:50:52.340] fastbot native : library load!
[Fastbot][2021-12-31 13:50:52.360] 

[Fastbot][2021-12-31 13:50:52.369] // the top activity is com.miui.home.launcher.Launcher, not testing app, need inject restart app
[Fastbot][2021-12-31 13:50:52.376] Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.chehejia.oc.m01/.business.home.LoginActivity;end
[Fastbot][2021-12-31 13:50:52.386]     // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.chehejia.oc.m01/.business.home.LoginActivity } in package com.chehejia.oc.m01
[Fastbot][2021-12-31 13:50:52.396]     // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.chehejia.oc.m01/.business.home.LoginActivity } in package com.chehejia.oc.m01
[Fastbot][2021-12-31 13:50:52.415] // current activity is com.chehejia.oc.m01.view.gui.home.HomeActivity
[Fastbot][2021-12-31 13:50:52.430] Sleeping for 6000 milliseconds
[Fastbot][2021-12-31 13:50:58.474] // Eventid: 3
[Fastbot][2021-12-31 13:50:58.570] action type: BACK
[Fastbot][2021-12-31 13:50:58.570] rpc cost time: 39
[Fastbot][2021-12-31 13:50:58.658]  event time:219
[Fastbot][2021-12-31 13:50:58.660] :Sending rotation degree=0, persist=false
[Fastbot][2021-12-31 13:50:58.707] :Sending Key (ACTION_DOWN): 4    // KEYCODE_BACK
[Fastbot][2021-12-31 13:50:58.711] // Monkey is over!
[Fastbot][2021-12-31 13:50:58.712] :Sending rotation degree=0, persist=false
[Fastbot][2021-12-31 13:50:58.729] Internal error
java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
	at android.os.Parcel.createException(Parcel.java:2074)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.os.Parcel.readException(Parcel.java:1990)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:925)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:886)
	at com.android.commands.monkey.o.a(SourceFile:133)
	at com.android.commands.monkey.Monkey.f(SourceFile:1503)
	at com.android.commands.monkey.Monkey.a(SourceFile:860)
	at com.android.commands.monkey.Monkey.main(SourceFile:454)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.input.InputManagerService.injectInputEventInternal(InputManagerService.java:730)
	at com.android.server.input.InputManagerService.injectInputEvent(InputManagerService.java:704)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:422)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

[Fastbot][2021-12-31 13:50:58.733] Please report this bug issue to github

**Comment by geron-cn** [comment]
hello， 参考 readme 中 Q&A， 设置下系统设置即可。
