### ISSUE TITLE
如何同时在多台手机上同时运行？

### ISSUE THREAD

**Issue by zhangkeliang2020** [bytedance/Fastbot_Android#12]
手边有3台安卓测试机，同时连接到电脑，如何同时启动fastbot测试？

**Comment by mengbin890815** [comment]
> 手边有3台安卓测试机，同时连接到电脑，如何同时启动fastbot测试？

你的可以正常跑吗，我跑的会漏掉很多按钮，覆盖率很低很低

**Comment by zhangkeliang2020** [comment]
覆盖率还行，1小时覆盖率27%

**Comment by mengbin890815** [comment]
> 覆盖率还行，1小时覆盖率27%

你的会遍历所有的功能吗，我跑的时候，只在几个tag页跳来跳去，很多按钮都不点。

**Comment by zhangzhao4444** [comment]
adb -s deviceid shell xxx
