### ISSUE TITLE
无法跑输入法类app的稳定性测试

### ISSUE THREAD

**Issue by gangliu6** [bytedance/Fastbot_Android#124]
因本身app就是输入法类，使用该工具在跑稳定性测试过程中，会被切换输入法；导致稳定性测试无效。

请问，是否可以不使用默认的ADBKeyBoard？

**Comment by zhangzhao4444** [comment]
备忘，输入法类比较特殊，持续跟进下这个需求

**Comment by zhangzhao4444** [comment]
暂时不考虑支持此类测试
