### ISSUE TITLE
待测应用一直在启动画面，但是进不去，Monkey一直在调用RESTART

### ISSUE THREAD

**Issue by rockcaostar** [bytedance/Fastbot_Android#129]
我的应用可能Splash停留时间有点长发现Monkey运行随机事件会一直反复启动，但是无法进入主页面了，Monkey被挡在待测外了
跑了3个小时，将近有180多次都在反复重启但是进不去

[Fastbot][2022-01-21 13:08:06.048] action type: RESTART
[Fastbot][2022-01-21 13:08:06.049] rpc cost time: 2
[Fastbot][2022-01-21 13:08:06.049] press HOME before app kill
[Fastbot][2022-01-21 13:08:06.050] Stop all packages, retry count 9
[Fastbot][2022-01-21 13:08:06.051] Try to stop package com.test.rocktestar.fam
[Fastbot][2022-01-21 13:08:07.081]  event time:1059
[Fastbot][2022-01-21 13:08:07.084] :Sending rotation degree=0, persist=false
[Fastbot][2022-01-21 13:08:07.205] :Sending Key (ACTION_DOWN): 3    // KEYCODE_HOME
[Fastbot][2022-01-21 13:08:07.213] :Sending Key (ACTION_UP): 3    // KEYCODE_HOME
[Fastbot][2022-01-21 13:08:07.262] Sleeping for 5000 milliseconds
/Users/gdccekai/Library/Android/sdk/platform-tools/adb -s JPFDU19218009151 shell "ps | grep monkey"
[Fastbot][2022-01-21 13:08:12.267] Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.test.rocktestar.fam/com.test.rocktestar.ui.SplashActivity;end
[Fastbot][2022-01-21 13:08:12.284] // the top activity is com.test.rocktestar.ui.SplashActivity, phone capture activity is com.huawei.camera.ThirdCamera
[Fastbot][2022-01-21 13:08:12.285]     // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.test.rocktestar.fam/com.test.rocktestar.ui.SplashActivity } in package com.test.rocktestar.fam
[Fastbot][2022-01-21 13:08:12.327] Sleeping for 2000 milliseconds
[Fastbot][2022-01-21 13:08:14.335] Sleeping for 895 milliseconds
[Fastbot][2022-01-21 13:08:14.797] // the top activity is com.test.rocktestar.ui.MainActivity, phone capture activity is com.huawei.camera.ThirdCamera
[Fastbot][2022-01-21 13:08:14.798]     // Rejecting start of Intent { cmp=com.test.rocktestar.fam/com.test.rocktestar.ui.MainActivity } in package com.test.rocktestar.fam
[Fastbot][2022-01-21 13:08:15.234] // the top activity is com.huawei.android.launcher.unihome.UniHomeLauncher, not testing app, need inject restart app
[Fastbot][2022-01-21 13:08:15.235] Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.test.rocktestar.fam/com.test.rocktestar.ui.SplashActivity;end
[Fastbot][2022-01-21 13:08:15.240] // the top activity is com.test.rocktestar.ui.SplashActivity, phone capture activity is com.huawei.camera.ThirdCamera
[Fastbot][2022-01-21 13:08:15.241]     // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.test.rocktestar.fam/com.test.rocktestar.ui.SplashActivity } in package com.test.rocktestar.fam
[Fastbot][2022-01-21 13:08:15.290] Sleeping for 2000 milliseconds
[Fastbot][2022-01-21 13:08:17.029] // the top activity is com.test.rocktestar.ui.MainActivity, phone capture activity is com.huawei.camera.ThirdCamera
[Fastbot][2022-01-21 13:08:17.029]     // Rejecting start of Intent { cmp=com.test.rocktestar.fam/com.test.rocktestar.ui.MainActivity } in package com.test.rocktestar.fam
[Fastbot][2022-01-21 13:08:17.303] // Eventid: 51757
[Fastbot][2022-01-21 13:08:17.315] action type: RESTART
[Fastbot][2022-01-21 13:08:17.315] rpc cost time: 2
[Fastbot][2022-01-21 13:08:17.316] Stop all packages, retry count 9
[Fastbot][2022-01-21 13:08:17.316] Try to stop package com.test.rocktestar.fam

**Comment by zhangzhao4444** [comment]
同学有配置什么activity黑白名单吗？

**Comment by zhangzhao4444** [comment]
// Rejecting start of Intent { cmp=com.test.rocktestar.fam/com.test.rocktestar.ui.MainActivity } in package com.test.rocktestar.fam

**Comment by rockcaostar** [comment]
配置了黑白名单 
















在 2022-02-21 15:42:52，"zhangzhao" ***@***.***> 写道：

同学有配置什么activity黑白名单吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Secret111baby** [comment]
你好，碰到类似问题，请问怎么解决的呢

**Comment by zhangzhao4444** [comment]
把黑名单去掉？
