### ISSUE TITLE
黑名单无效；每次遍历都会漏掉很多，遍历不全

### ISSUE THREAD

**Issue by mengbin890815** [bytedance/Fastbot_Android#13]
1. 黑名单abl.strings设置的，有时会无效，还是会进入相应的activity
2. 每次遍历都会漏掉很多，覆盖了10%以下，有高于10%的吗，为什么我跑的这么差

**Comment by zhangzhao4444** [comment]
这个是个优化问题，想100%遍历是很难的。 10%是总activity覆盖率吗？ 通常apk会包含大量ui层面无法触发到的activity

**Comment by mengbin890815** [comment]
> 这个是个优化问题，想100%遍历是很难的。 10%是总activity覆盖率吗？ 通常apk会包含大量ui层面无法触发到的activity

你好，我们需求是按顺序遍历UI上的每个可点击的控件，然后进入相应的页面，并截图。然后切换语言再进行同样的操作，顺序需要保持一样。请问这个是不是不能满足这个需求还。
