### ISSUE TITLE
monkey测试中，发生了crash，但crash-dump.log文件中并未记录

### ISSUE THREAD

**Issue by fancker1992** [bytedance/Fastbot_Android#137]
1、bugly中可以查看到对应的crash日志，但是crash-dump.log文件中并没有统计上

2、monkey命令：
<img width="964" alt="11d081c1dfdafce5ba7ec804261f39d1" src="https://user-images.githubusercontent.com/24252503/154886170-0cb75073-e739-4eaf-8f5a-9b1def529471.png">

3、使用说明文档：
<img width="565" alt="55ec5ff1fd6751a1ff8117674243eab1" src="https://user-images.githubusercontent.com/24252503/154886188-65e2279f-cb60-44b5-8e27-7c0aa775907c.png">

**Comment by zhangzhao4444** [comment]
可以问下研发，app内部是否有做崩溃处理截断

**Comment by zhangzhao4444** [comment]
通常情况 ，如果app内有机制抓取crash 并截断了后续系统对crash的处理流程，这样就获取不到。 bugly上有的话说明app内有接入一套crash处理流程了。
