### ISSUE TITLE
不能按max.path.actions执行用例

### ISSUE THREAD

**Issue by yinianwuming** [bytedance/Fastbot_Android#139]
![image](https://user-images.githubusercontent.com/100359651/155533099-4e8752f4-a6df-4e3b-8f3e-f2192053c0cd.png)
向文本框输入文本，但是执行过程中并未执行

**Comment by yinianwuming** [comment]
![image](https://user-images.githubusercontent.com/100359651/155533387-f7563615-0cc3-4239-9c6c-b0fbd8704f4d.png)

**Comment by zhangzhao4444** [comment]
这个请确认是否安装并激活了adbkeyboard？

**Comment by zhangzhao4444** [comment]
2.3.23.0810.1705-git fixed
