### ISSUE TITLE
荣耀magic 2(鸿蒙操作系统)执行时报下面这个崩溃

### ISSUE THREAD

**Issue by pxrgod** [bytedance/Fastbot_Android#141]
[Fastbot][2022-03-02 16:05:44.768] Internal error
java.lang.UnsatisfiedLinkError: No implementation found for boolean com.bytedance.fastbot.AiClient.nkksdhdk(java.lang.String, float, float) (tried Java_com_bytedance_fastbot_AiClient_nkksdhdk and Java_com_bytedance_fastbot_AiClient_nkksdhdk__Ljava_lang_String_2FF)
        at com.bytedance.fastbot.AiClient.nkksdhdk(Native Method)
        at com.bytedance.fastbot.AiClient.a(SourceFile:122)
        at com.android.commands.monkey.x.a(SourceFile:616)
        at com.android.commands.monkey.x.a(SourceFile:5658)
        at com.android.commands.monkey.x.b(SourceFile:1037)
        at com.android.commands.monkey.x.a(SourceFile:994)
        at com.android.commands.monkey.x.z(SourceFile:940)
        at com.android.commands.monkey.x.k(SourceFile:395)
        at com.android.commands.monkey.Monkey.f(SourceFile:1510)
        at com.android.commands.monkey.Monkey.a(SourceFile:867)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[Fastbot][2022-03-02 16:05:44.777] Please report this bug issue to github

**Comment by zhangzhao4444** [comment]
https://github.com/bytedance/Fastbot_Android/issues/138 同学参考下这个，看能解决吗？ 一般so都是放错了位置

**Comment by pxrgod** [comment]
![image](https://user-images.githubusercontent.com/17092284/159922718-477f2d8e-ab37-4506-bc7a-9374655b8f50.png)
HWTNY:/data/local/tmp/arm64-v8a $ ls
libfastbot_native.so
我看了下目录的，这个目录下是有so的

**Comment by pxrgod** [comment]
> #138 同学参考下这个，看能解决吗？ 一般so都是放错了位置

HWTNY:/data/local/tmp/arm64-v8a $ ls
libfastbot_native.so
我看了下目录的，这个目录下是有so的

**Comment by wangchy0927** [comment]
Pixel 4也是同样的问题，华为 小米 什么的没问题

**Comment by wangchy0927** [comment]
[Fastbot][2022-09-05 18:31:45.897]  @Version: 2.2.02.0708.1723-git
[Fastbot][2022-09-05 18:31:48.962] // phone info： Google_Pixel 4_13
[Fastbot][2022-09-05 18:31:48.962] // runing fastbot
[Fastbot][2022-09-05 18:31:48.967] InputMethod ID: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
[Fastbot][2022-09-05 18:31:48.968] InputMethod ID: com.google.android.tts/com.google.android.apps.speech.tts.googletts.settings.asr.voiceime.VoiceInputMethodService
[Fastbot][2022-09-05 18:31:48.973] // device serial number is 99151FFAZ00G90
[Fastbot][2022-09-05 18:31:48.996] // device uuid is 51ff66af-1195-4e4f-9b2f-1a2931df929e
[Fastbot][2022-09-05 18:31:50.082] // init with reuse agent
[Fastbot][2022-09-05 18:31:50.086] fastbot native : library load!
[Fastbot][2022-09-05 18:31:50.089] 

[Fastbot][2022-09-05 18:31:50.091] // current activity is cn.wps.moffice.main.local.HomeRootActivity
[Fastbot][2022-09-05 18:31:50.099] // Eventid: 1
[Fastbot][2022-09-05 18:31:50.133] action type: CLICK
[Fastbot][2022-09-05 18:31:50.133] rpc cost time: 11
[Fastbot][2022-09-05 18:31:50.135] // Monkey is over!
java.lang.UnsatisfiedLinkError: No implementation found for boolean com.bytedance.fastbot.AiClient.nkksdhdk(java.lang.String, float, float) (tried Java_com_bytedance_fastbot_AiClient_nkksdhdk and Java_com_bytedance_fastbot_AiClient_nkksdhdk__Ljava_lang_String_2FF)
	at com.bytedance.fastbot.AiClient.nkksdhdk(Native Method)
	at com.bytedance.fastbot.AiClient.a(SourceFile:122)
	at com.android.commands.monkey.x.a(SourceFile:617)
	at com.android.commands.monkey.x.a(SourceFile:5659)
	at com.android.commands.monkey.x.b(SourceFile:1038)
	at com.android.commands.monkey.x.a(SourceFile:995)
	at com.android.commands.monkey.x.I(SourceFile:941)
	at com.android.commands.monkey.x.l(SourceFile:396)
	at com.android.commands.monkey.Monkey.f(SourceFile:1510)
	at com.android.commands.monkey.Monkey.a(SourceFile:867)
	at com.android.commands.monkey.Monkey.main(SourceFile:458)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
[Fastbot][2022-09-05 18:31:50.144] Internal error
[Fastbot][2022-09-05 18:31:50.146] Please report this bug issue to github

**Comment by wangchy0927** [comment]
安卓13好像都是这个问题

**Comment by zhangzhao4444** [comment]
> [Fastbot][2022-09-05 18:31:45.897] @Version: 2.2.02.0708.1723-git [Fastbot][2022-09-05 18:31:48.962] // phone info： Google_Pixel 4_13 [Fastbot][2022-09-05 18:31:48.962] // runing fastbot [Fastbot][2022-09-05 18:31:48.967] InputMethod ID: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME [Fastbot][2022-09-05 18:31:48.968] InputMethod ID: com.google.android.tts/com.google.android.apps.speech.tts.googletts.settings.asr.voiceime.VoiceInputMethodService [Fastbot][2022-09-05 18:31:48.973] // device serial number is 99151FFAZ00G90 [Fastbot][2022-09-05 18:31:48.996] // device uuid is 51ff66af-1195-4e4f-9b2f-1a2931df929e [Fastbot][2022-09-05 18:31:50.082] // init with reuse agent [Fastbot][2022-09-05 18:31:50.086] fastbot native : library load! [Fastbot][2022-09-05 18:31:50.089]
> 
> [Fastbot][2022-09-05 18:31:50.091] // current activity is cn.wps.moffice.main.local.HomeRootActivity [Fastbot][2022-09-05 18:31:50.099] // Eventid: 1 [Fastbot][2022-09-05 18:31:50.133] action type: CLICK [Fastbot][2022-09-05 18:31:50.133] rpc cost time: 11 [Fastbot][2022-09-05 18:31:50.135] // Monkey is over! java.lang.UnsatisfiedLinkError: No implementation found for boolean com.bytedance.fastbot.AiClient.nkksdhdk(java.lang.String, float, float) (tried Java_com_bytedance_fastbot_AiClient_nkksdhdk and Java_com_bytedance_fastbot_AiClient_nkksdhdk__Ljava_lang_String_2FF) at com.bytedance.fastbot.AiClient.nkksdhdk(Native Method) at com.bytedance.fastbot.AiClient.a(SourceFile:122) at com.android.commands.monkey.x.a(SourceFile:617) at com.android.commands.monkey.x.a(SourceFile:5659) at com.android.commands.monkey.x.b(SourceFile:1038) at com.android.commands.monkey.x.a(SourceFile:995) at com.android.commands.monkey.x.I(SourceFile:941) at com.android.commands.monkey.x.l(SourceFile:396) at com.android.commands.monkey.Monkey.f(SourceFile:1510) at com.android.commands.monkey.Monkey.a(SourceFile:867) at com.android.commands.monkey.Monkey.main(SourceFile:458) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355) [Fastbot][2022-09-05 18:31:50.144] Internal error [Fastbot][2022-09-05 18:31:50.146] Please report this bug issue to github

这个so是不是没更新？ java用了新版，so还是老版本， nkksdhdk这个func没找到
