### ISSUE TITLE
执行aapt2 dump  --values strings命名报错

### ISSUE THREAD

**Issue by happyMeiyo** [bytedance/Fastbot_Android#145]
![image](https://user-images.githubusercontent.com/22342835/157578360-f4f92c7a-c972-42fe-9e21-eb4a8b70b1e8.png)
你好，执行命令aapt2 dump  --values strings报错。

另外，请问添加max.valid.strings到手机的作用是什么？添加限定词这里不太理解，谢谢🙏

**Comment by zhangzhao4444** [comment]
请更新你的aapt2 或者查询下当前aapt命令如何获取apk中的string。限定词用于提取页面中特征。
