### ISSUE TITLE
配置文件max.widget.black，还是会点击设置，导致App退出

### ISSUE THREAD

**Issue by happyMeiyo** [bytedance/Fastbot_Android#146]
![image](https://user-images.githubusercontent.com/22342835/157586895-dd1e263f-a412-4731-a9ae-516d9cd14924.png)
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/22342835/157587196-cf817ce6-5bf0-43c5-a15c-e9624bd0064f.png">
你好，配置如上图，但是执行过程中，仍然会点击button设置，导致退出App
手机是vivo Y51s，Android版本是10

**Comment by lzus** [comment]
同遇到这个问题，黑名单不生效，用的小米手机android 10

**Comment by znrabbit** [comment]
同问题，华为mate 30 pro 和华为mate 40 pro

**Comment by DoReMi115** [comment]
荣耀x10，华为p30，同此问题。

**Comment by zhangzhao4444** [comment]
activity配错了，请再对照手册检查一下

**Comment by zhangzhao4444** [comment]
中间多了个 "/"
