### ISSUE TITLE
请问一下在max.widget.black如何配置屏蔽响应系统的back键

### ISSUE THREAD

**Issue by Jeremy-Lin** [bytedance/Fastbot_Android#150]
想固定在某个activity中执行Monkey, 可是执行起来经常响应系统back键， 跳出了目标activity

**Comment by zhangzhao4444** [comment]
这个目前还不支持，可能能行的是在跳出后的activity中配置自定义事件再回到待测activity

**Comment by lzus** [comment]
可否像https://github.com/zhangzhao4444/Maxim
一样，提供back事件的比例？ 

mix 增加 back event 默认事件占比10%

  --pct-back 0 （设置占比0）

**Comment by Jeremy-Lin** [comment]
> 

请问一下如何配置再回到待测activity？

**Comment by zhangzhao4444** [comment]
会自动回到待测app的

**Comment by zhangzhao4444** [comment]
> 

@lzus 算法有一层默认的兜底，所有action都操作完会执行back

**Comment by zhangzhao4444** [comment]
> > 
> 
> 请问一下如何配置再回到待测activity？

跳出app后会自动跳回app的

**Comment by zhangzhao4444** [comment]
https://github.com/bytedance/Fastbot_Android/issues/56  同类需求
