### ISSUE TITLE
使用xpath跳转微信、微博登录时，遇到Rejecting start of Intent { cmp=com.tencent.mm/.plugin.base.stub.WXEntryActivity } in package com.tencent.mm

### ISSUE THREAD

**Issue by buder-cp** [bytedance/Fastbot_Android#151]
按照中文手册中配置好了max.xpath.actions，填写完毕相关参数后push到sdcard。本页面的其他按钮都可以点击到，但是微博和微信登录的点击后，无法跳转，报错如下：

[Fastbot][2022-03-23 14:05:21.599] Sleeping for 895 milliseconds
[Fastbot][2022-03-23 14:05:22.504] // Eventid: 229
[Fastbot][2022-03-23 14:05:22.511] action type: CLICK
[Fastbot][2022-03-23 14:05:22.512] rpc cost time: 4
[Fastbot][2022-03-23 14:05:22.518]  event time:19
[Fastbot][2022-03-23 14:05:22.518] :Sending rotation degree=0, persist=false
[Fastbot][2022-03-23 14:05:22.539] :Sending Touch (ACTION_DOWN): 0:(564.0,3013.0)
[Fastbot][2022-03-23 14:05:22.543] :Sending Touch (ACTION_UP): 0:(564.0,3013.0)
[Fastbot][2022-03-23 14:05:22.545] Sleeping for 836 milliseconds
[Fastbot][2022-03-23 14:05:22.571] // the top activity is com.sina.weibo.SSOActivity, phone capture activity is com.android.camera.OneShotCamera
[Fastbot][2022-03-23 14:05:22.572]     // Rejecting start of Intent { cmp=com.sina.weibo/.SSOActivity } in package com.sina.weibo
[Fastbot][2022-03-23 14:05:22.576] // the top activity is com.sina.weibo.SSOActivity, phone capture activity is com.android.camera.OneShotCamera
[Fastbot][2022-03-23 14:05:22.576]     // Rejecting start of Intent { cmp=com.sina.weibo/.SSOActivity } in package com.sina.weibo
[Fastbot][2022-03-23 14:05:23.394] // Eventid: 233
[Fastbot][2022-03-23 14:05:23.401] action type: CLICK
[Fastbot][2022-03-23 14:05:23.402] rpc cost time: 3
[Fastbot]*** WARNING *** checkVirtualKeyboard: Input only once.
[Fastbot][2022-03-23 14:05:23.408]  event time:20
[Fastbot][2022-03-23 14:05:23.409] :Sending rotation degree=0, persist=false
[Fastbot][2022-03-23 14:05:23.426] :Sending Touch (ACTION_DOWN): 0:(909.0,2941.0)
[Fastbot][2022-03-23 14:05:23.429] :Sending Touch (ACTION_UP): 0:(909.0,2941.0)
[Fastbot][2022-03-23 14:05:23.443] Sleeping for 840 milliseconds
[Fastbot][2022-03-23 14:05:23.446] // the top activity is com.tencent.mm.plugin.base.stub.WXEntryActivity, phone capture activity is com.android.camera.OneShotCamera
[Fastbot][2022-03-23 14:05:23.446]     // Rejecting start of Intent { cmp=com.tencent.mm/.plugin.base.stub.WXEntryActivity } in package com.tencent.mm
[Fastbot][2022-03-23 14:05:23.448] // the top activity is com.tencent.mm.plugin.base.stub.WXEntryActivity, phone capture activity is com.android.camera.OneShotCamera
[Fastbot][2022-03-23 14:05:23.448]     // Rejecting start of Intent { cmp=com.tencent.mm/.plugin.base.stub.WXEntryActivity } in package com.tencent.mm
[Fastbot][2022-03-23 14:05:24.294] // Eventid: 237
[Fastbot][2022-03-23 14:05:24.302] action type: SCROLL_RIGHT_LEFT
[Fastbot][2022-03-23 14:05:24.304] rpc cost time: 5
[Fastbot][2022-03-23 14:05:24.309]  event time:21
[Fastbot][2022-03-23 14:05:24.310] :Sending rotation degree=0, persist=false
[Fastbot][2022-03-23 14:05:24.327] :Sending Touch (ACTION_DOWN): 0:(720.0,1600.0)
[Fastbot][2022-03-23 14:05:24.332] :Sending Touch (ACTION_MOVE): 0:(720.0,1600.0)
[Fastbot][2022-03-23 14:05:24.336] Wait Event for 20 milliseconds

![image](https://user-images.githubusercontent.com/19617838/159837677-05a61a96-b9c1-423b-8199-3ab0d773d90b.png)

**Comment by zhangzhao4444** [comment]
在max.config中配置max.allowStartActivityEscapeAny=true
然后push /sdcard
