### ISSUE TITLE
关于测试复用的问题

### ISSUE THREAD

**Issue by Kim-LL** [bytedance/Fastbot_Android#153]
一个手机跑了很久，想让这个手机的测试遍历数据文件如何提取，然后移植到其他手机上？

**Comment by geron-cn** [comment]
将 `/sdcard/fastbot_[packagename].fbm` 这个文件转存到其他手机即可

**Comment by renweizhen** [comment]
在手机/sdcard路径下没有找到fastbot_[packagename].fbm。全局搜索也没有fbm格式的文件。
另外，还有个问题：在/sdcard路径下有一些文件夹，命名是fastbot-[packagename]-robot-running-minutes-20，但是文件夹为空。

**Comment by geron-cn** [comment]
> 在手机/sdcard路径下没有找到fastbot_[packagename].fbm。全局搜索也没有fbm格式的文件。 另外，还有个问题：在/sdcard路径下有一些文件夹，命名是fastbot-[packagename]-robot-running-minutes-20，但是文件夹为空。

麻烦确认下使用的是最新版本么， 是否是带 libfastbot_native.so 这个版本
