### ISSUE TITLE
在配置文件max.widget.black，设置bounds的格式什么？

### ISSUE THREAD

**Issue by bnndy** [bytedance/Fastbot_Android#157]
如题，在配置文件max.widget.black，设置bounds的格式是怎么样的，麻烦举例说明

**Comment by tang-wangyisuifeng** [comment]
我设置为bounds: "0.5,0.9,0.7,1"，运行的时候好像都不行了

**Comment by zhangzhao4444** [comment]
bounds: "[x0,y0][x1,y1]"

**Comment by zer0e** [comment]
> bounds: "[x0,y0][x1,y1]"

@zhangzhao4444  你好，在 #19 中，bounds 是说设置成分割的四个浮点数，我两种试了都没有生效
