### ISSUE TITLE
--bugreport参数，需要传递参数值？

### ISSUE THREAD

**Issue by gavin-huangwang** [bytedance/Fastbot_Android#159]

**Comment by Sanmejie** [comment]
同问--bugreport 会把日志存哪？ 后面需要传值吗？

**Comment by gradient30** [comment]
说明里有写吧- -，有崩溃会生成 /sdcard/crash-dump.log

**Comment by Sanmejie** [comment]
> 说明里有写吧- -，有崩溃会生成/sdcard/crash-dump.log

确定不是 adb bugreport 而是普通的crash文件？ 不指定如果有崩溃也会生成/sdcard/crash-dump.log的

**Comment by gradient30** [comment]
> > 说明里有写吧- -，有崩溃会生成/sdcard/crash-dump.log
> 
> 确定不是 adb bugreport 而是普通的crash文件？ 不指定如果有崩溃也会生成/sdcard/crash-dump.log的

![image](https://user-images.githubusercontent.com/39947529/215938406-eb5e8fa0-af84-4cf2-9720-57e1317306ad.png)
我看帮助里是没有接参数的

**Comment by zhangzhao4444** [comment]
--bugreport 不需要参数的

**Comment by zhangzhao4444** [comment]
bugreport 相关文件会在--output-directory自定义保存目录下生成，或者默认存在
/sdcard
