### ISSUE TITLE
run with warning

### ISSUE THREAD

**Issue by iopass4** [bytedance/Fastbot_Android#16]
[WARNING] Got IOException performing flip : java.io.FileNotFoundException: /dev/input/event0: open failed: EACCES (Permission denied)
[1610372373372]     // Injection Failed com.android.commands.monkey.k@b8397b5

**Comment by zhangzhao4444** [comment]
需要更详细的日志，仅这个event injection failed吗？ 还是所有event?

**Comment by KG-TD** [comment]
hi，我也遇到这个情况。 请问大佬们知道这个错误是什么含义吗？
