### ISSUE TITLE
没有启动页的App能去做适配吗？

### ISSUE THREAD

**Issue by pengbeilin** [bytedance/Fastbot_Android#167]
你好，就是fastbot跟monkey一样，没有启动页(android.intent.category.LAUNCHER)的应用，没有办法去执行测试，可不可以加一个activity的启动参数，如果有这个参数，就用这个activity启动然后去执行测试

**Comment by zhangzhao4444** [comment]
这个可查询下 原生monkey的用法，也支持 -c 配置categories  通过特定的intent来启动。  不过更建议实现一个launcher去启动，fastbot自动组合了lanucher的intent
