### ISSUE TITLE
如何理解截图以及UI hierarchy文件的文件名

### ISSUE THREAD

**Issue by zhaoxu-zhang** [bytedance/Fastbot_Android#169]
请问现在dump的截图以及UI hierarchy文件的文件名应该如何理解呢？如：step-1--g0a5-1655160668573.png，可以理解第一部分指的是当前为第几个step, 请问后面部分应该对应什么？谢谢！ #37

**Comment by zhangzhao4444** [comment]
step-1 第一步

**Comment by zhangzhao4444** [comment]
g0a5，在有向图中第一个state状态下，执行的这个状态下的第5个action
