### ISSUE TITLE
请问是否可以根据monkey的seed重跑测试呢？

### ISSUE THREAD

**Issue by astrid77** [bytedance/Fastbot_Android#171]
![image](https://user-images.githubusercontent.com/24728556/175452948-dc79a848-6548-4e34-b8bb-1d10f7e63901.png)
我尝试重跑测试，由于之前的测试中有自定义事件序列，加入了账号验证码的输入，貌似直接seed重跑会找不到参数值？
![image](https://user-images.githubusercontent.com/24728556/175453259-03b03c11-f012-4a3a-8ce4-7363d2362b8a.png)

**Comment by zhangzhao4444** [comment]
sorry不支持seed
