### ISSUE TITLE
agent=reuseq模式下  fastbot执行了几次后无法执行

### ISSUE THREAD

**Issue by lionel126** [bytedance/Fastbot_Android#172]
我用过两台手机执行fastbot  都在执行了几天后（每天跑1次或多次） 再也不能执行了
如图：日志停留在 fastbot native : library load!
![image](https://user-images.githubusercontent.com/3871189/176123018-ece35d42-f3c3-4e24-91ae-ae404ce4f721.png)

把--agent reuseq 换成 --agent robot后正常
文档注明了reuseq代表遍历模式   robot呢？agent还有哪些值 ？

**Comment by wangxa97** [comment]
可以看下我提的issue，解决了
