### ISSUE TITLE
运行demo提示 UiAutomationService已经注册

### ISSUE THREAD

**Issue by LitongGao** [bytedance/Fastbot_Android#173]
bogon:Fastbot_Android gaolitong$ adb -s SCSOCIHYSW6HUWPR shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.hnhuyu.chatlive --agent reuseq --running-minutes 10 --throttle 10 -v -v
▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░▌ ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀▀▀  ▀▀▀▀█░█▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀█░▌ ▀▀▀▀█░█▀▀▀▀
▐░▌          ▐░▌       ▐░▌▐░▌               ▐░▌     ▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌
▐░█▄▄▄▄▄▄▄▄▄ ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄▄▄      ▐░▌     ▐░█▄▄▄▄▄▄▄█░▌▐░▌       ▐░▌     ▐░▌
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌     ▐░▌     ▐░░░░░░░░░░▌ ▐░▌       ▐░▌     ▐░▌
▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌ ▀▀▀▀▀▀▀▀▀█░▌     ▐░▌     ▐░█▀▀▀▀▀▀▀█░▌▐░▌       ▐░▌     ▐░▌
▐░▌          ▐░▌       ▐░▌          ▐░▌     ▐░▌     ▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌
▐░▌          ▐░▌       ▐░▌ ▄▄▄▄▄▄▄▄▄█░▌     ▐░▌     ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄█░▌     ▐░▌
▐░▌          ▐░▌       ▐░▌▐░░░░░░░░░░░▌     ▐░▌     ▐░░░░░░░░░░▌ ▐░░░░░░░░░░░▌     ▐░▌
 ▀            ▀         ▀  ▀▀▀▀▀▀▀▀▀▀▀       ▀       ▀▀▀▀▀▀▀▀▀▀   ▀▀▀▀▀▀▀▀▀▀▀       ▀
[Fastbot][2022-06-30 18:31:45.205]  @Version: 2.2.01.1101.2108-git
[Fastbot][2022-06-30 18:31:45.257] // Monkey: seed=1656736332422 count=1000

[Fastbot][2022-06-30 18:31:45.260] // AllowPackage: com.hnhuyu.chatlive
[Fastbot][2022-06-30 18:31:45.261] // IncludeCategory: android.intent.category.LAUNCHER
[Fastbot][2022-06-30 18:31:45.262] // IncludeCategory: android.intent.category.MONKEY
[Fastbot][2022-06-30 18:31:45.359] // Selecting main activities from category android.intent.category.LAUNCHER
[Fastbot][2022-06-30 18:31:45.360] //   - NOT USING main activity com.android.gallery3d.vivo.GalleryTabActivity (from package com.vivo.gallery)
[Fastbot][2022-06-30 18:31:45.361] //   - NOT USING main activity com.android.bbkmusic.WidgetToTrackActivity (from package com.android.bbkmusic)
[Fastbot][2022-06-30 18:31:45.362] //   - NOT USING main activity com.android.activity.ReclistActivity (from package com.android.bbksoundrecorder)
[Fastbot][2022-06-30 18:31:45.363] //   - NOT USING main activity com.android.camera.CameraActivity (from package com.android.camera)
[Fastbot][2022-06-30 18:31:45.364] //   - NOT USING main activity com.android.contacts.DialtactsContactsEntryActivity (from package com.android.contacts)
[Fastbot][2022-06-30 18:31:45.365] //   - NOT USING main activity com.android.dialer.TwelveKeyDialer (from package com.android.dialer)
[Fastbot][2022-06-30 18:31:45.366] //   - NOT USING main activity com.android.mms.ui.ConversationList (from package com.android.mms)
[Fastbot][2022-06-30 18:31:45.368] //   - NOT USING main activity com.android.settings.Settings (from package com.android.settings)
[Fastbot][2022-06-30 18:31:45.370] //   - NOT USING main activity com.bbk.calendar.MainActivity (from package com.bbk.calendar)
[Fastbot][2022-06-30 18:31:45.371] //   - NOT USING main activity com.bbk.theme.Theme (from package com.bbk.theme)
[Fastbot][2022-06-30 18:31:45.373] //   - NOT USING main activity com.chaozh.iReader.ui.activity.WelcomeActivity (from package com.chaozh.iReader)
[Fastbot][2022-06-30 18:31:45.376] //   - NOT USING main activity com.mobile.iroaming.activity.MainActivity (from package com.mobile.iroaming)
[Fastbot][2022-06-30 18:31:45.378] //   - NOT USING main activity com.vivo.health.main.activity.GuideActivity (from package com.vivo.health)
[Fastbot][2022-06-30 18:31:45.379] //   - NOT USING main activity com.android.vending.AssetBrowserActivity (from package com.android.vending)
[Fastbot][2022-06-30 18:31:45.380] //   - NOT USING main activity com.tencent.pangu.link.SplashActivity (from package com.tencent.android.qqdownloader)
[Fastbot][2022-06-30 18:31:45.381] //   - NOT USING main activity com.vivo.vhome.ui.VHomeActivity (from package com.vivo.vhome)
[Fastbot][2022-06-30 18:31:45.383] //   - NOT USING main activity com.android.BBKClock.Timer (from package com.android.BBKClock)
[Fastbot][2022-06-30 18:31:45.384] //   - NOT USING main activity com.android.VideoPlayer.VideoPlayer (from package com.android.VideoPlayer)
[Fastbot][2022-06-30 18:31:45.385] //   - NOT USING main activity com.android.bbkcalculator.Calculator (from package com.android.bbkcalculator)
[Fastbot][2022-06-30 18:31:45.387] //   - NOT USING main activity com.android.filemanager.FileManagerActivity (from package com.android.filemanager)
[Fastbot][2022-06-30 18:31:45.388] //   - NOT USING main activity com.android.notes.Notes (from package com.android.notes)
[Fastbot][2022-06-30 18:31:45.389] //   - NOT USING main activity com.bbk.appstore.ui.AppStore (from package com.bbk.appstore)
[Fastbot][2022-06-30 18:31:45.390] //   - NOT USING main activity com.bbk.cloud.activities.BBKCloudHomeScreen (from package com.bbk.cloud)
[Fastbot][2022-06-30 18:31:45.391] //   - NOT USING main activity com.iqoo.secure.MainGuideActivity (from package com.iqoo.secure)
[Fastbot][2022-06-30 18:31:45.392] //   - NOT USING main activity com.vivo.Tips.MainActivity (from package com.vivo.Tips)
[Fastbot][2022-06-30 18:31:45.394] //   - NOT USING main activity com.vivo.agent.view.activities.JoviHomeNewActivity (from package com.vivo.agent)
[Fastbot][2022-06-30 18:31:45.395] //   - NOT USING main activity com.vivo.browser.BrowserActivity (from package com.vivo.browser)
[Fastbot][2022-06-30 18:31:45.396] //   - NOT USING main activity com.vivo.compass.CalibrationActivity (from package com.vivo.compass)
[Fastbot][2022-06-30 18:31:45.397] //   - NOT USING main activity com.vivo.easyshare.activity.SplashScreenActivity (from package com.vivo.easyshare)
[Fastbot][2022-06-30 18:31:45.398] //   - NOT USING main activity com.vivo.email.activity.Welcome (from package com.vivo.email)
[Fastbot][2022-06-30 18:31:45.399] //   - NOT USING main activity com.vivo.game.ui.LogoActivity (from package com.vivo.game)
[Fastbot][2022-06-30 18:31:45.400] //   - NOT USING main activity com.vivo.space.ui.LogoActivity (from package com.vivo.space)
[Fastbot][2022-06-30 18:31:45.401] //   - NOT USING main activity com.vivo.wallet.StartPageActivity (from package com.vivo.wallet)
[Fastbot][2022-06-30 18:31:45.403] //   - NOT USING main activity com.vivo.weather.WeatherMain (from package com.vivo.weather)
[Fastbot][2022-06-30 18:31:45.404] //   - NOT USING main activity com.alibaba.android.rimet.biz.LaunchHomeActivity (from package com.alibaba.android.rimet)
[Fastbot][2022-06-30 18:31:45.405] //   - NOT USING main activity com.meelive.ingkee.launcher.ui.IngkeeLauncher (from package com.billion.qianxi)
[Fastbot][2022-06-30 18:31:45.407] //   - NOT USING main activity com.cisco.anyconnect.ui.PrimaryActivity (from package com.cisco.anyconnect.vpn.android.avf)
[Fastbot][2022-06-30 18:31:45.408] //   - NOT USING main activity com.github.uiautomator.MainActivity (from package com.github.uiautomator)
[Fastbot][2022-06-30 18:31:45.409] //   - NOT USING main activity com.google.android.apps.authenticator.AuthenticatorActivity (from package com.google.android.apps.authenticator2)
[Fastbot][2022-06-30 18:31:45.410] //   + Using main activity com.hnhuyu.chatlive.launcher.ChatLiveNewSplash (from package com.hnhuyu.chatlive)
[Fastbot][2022-06-30 18:31:45.411] //   - NOT USING main activity com.inke.inf.kae.MainActivity (from package com.inke.inf.kae)
[Fastbot][2022-06-30 18:31:45.412] //   - NOT USING main activity com.meelive.ingkee.launcher.ui.IngkeeLauncher (from package com.meelive.ingkee)
[Fastbot][2022-06-30 18:31:45.413] //   - NOT USING main activity com.oppo.market.activity.MainActivity (from package com.oppo.market)
[Fastbot][2022-06-30 18:31:45.415] //   - NOT USING main activity com.tencent.mobileqq.activity.SplashActivity (from package com.tencent.mobileqq)
[Fastbot][2022-06-30 18:31:45.416] //   - NOT USING main activity com.unity3d.player.UnityPlayerActivity (from package com.tencent.wetest.demo)
[Fastbot][2022-06-30 18:31:45.417] //   - NOT USING main activity com.v2cross.shadowrocket.ui.MainActivity (from package com.v2cross.proxy)
[Fastbot][2022-06-30 18:31:45.418] //   - NOT USING main activity com.yyhd.happywolf.view.splash.GSSplashActivity (from package com.yyhd.happywolf)
[Fastbot][2022-06-30 18:31:45.428] // Selecting main activities from category android.intent.category.MONKEY
[Fastbot][2022-06-30 18:31:45.430] //   - NOT USING main activity com.android.settings.Settings$RunningServicesActivity (from package com.android.settings)
[Fastbot][2022-06-30 18:31:45.431] //   - NOT USING main activity com.android.settings.Settings$StorageUseActivity (from package com.android.settings)
[Fastbot][2022-06-30 18:31:45.432] //   - NOT USING main activity com.bbk.launcher2.Launcher (from package com.bbk.launcher2)
[Fastbot][2022-06-30 18:31:45.433] //   - NOT USING main activity com.bbk.scene.launcher.theme.SceneLauncherThemeMainActivity (from package com.bbk.scene.launcher.theme)
[Fastbot][2022-06-30 18:31:45.434] //   - NOT USING main activity com.iqoo.engineermode.EngineerMode (from package com.iqoo.engineermode)
[Fastbot][2022-06-30 18:31:45.436] //   - NOT USING main activity com.vivo.systemui.statusbar.notification.settings.StatusbarSettingActivity (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.437] //   - NOT USING main activity com.vivo.systemui.statusbar.notification.settings.channels.NotificationSettingsActivity (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.438] //   - NOT USING main activity com.vivo.systemui.navigation.settings.NavigationSettingsActivity (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.439] //   - NOT USING main activity com.vivo.systemui.navigation.settings.NavigationStyleActivity (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.441] //   - NOT USING main activity com.vivo.systemui.navigation.settings.GestureOrderActivity (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.442] //   - NOT USING main activity com.vivo.systemui.navigation.settings.GestureStyleActivity (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.443] //   - NOT USING main activity com.vivo.systemui.navigation.settings.SwitchAppActivity (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.444] //   - NOT USING main activity com.vivo.systemui.navigation.settings.NavigationLandscapePositionActivity (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.445] //   - NOT USING main activity com.vivo.systemui.navigation.settings.FullScreenDoubleSlideActivity (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.446] //   - NOT USING main activity com.vivo.systemui.navigation.settings.AboutHomeIndicatorActivity (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.448] //   - NOT USING main activity com.vivo.systemui.navigation.settings.export.IndicatorDemoActivity (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.449] //   - NOT USING main activity com.vivo.keyguard.views.themes.nature.iconset.IconSettings (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.452] //   - NOT USING main activity com.android.keyguard.vivo.VivoConfirmActivity (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.453] //   - NOT USING main activity com.android.keyguard.vivo.VivoFaceRecommendDialog (from package com.android.systemui)
[Fastbot][2022-06-30 18:31:45.455] //   - NOT USING main activity com.vivo.shortcutcenter.ui.HomeActivity (from package com.vivo.shortcutcenter)
[Fastbot][2022-06-30 18:31:45.456] //   - NOT USING main activity com.vivo.upslide.recents.RecentsActivity (from package com.vivo.upslide)
[Fastbot][2022-06-30 18:31:48.461] // phone info： vivo_V1901A_9
[Fastbot][2022-06-30 18:31:48.462] // runing fastbot
[Fastbot][2022-06-30 18:31:48.630] InputMethod ID: com.sohu.inputmethod.sogou.vivo/.SogouIME
[Fastbot][2022-06-30 18:31:48.650] // device serial number is SCSOCIHYSW6HUWPR
[Fastbot][2022-06-30 18:31:48.682] Internal error
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@3c3ac95already registered!
	at android.os.Parcel.createException(Parcel.java:1958)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:416)
	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:399)
	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:97)
	at android.app.UiAutomation.connect(UiAutomation.java:234)
	at android.app.UiAutomation.connect(UiAutomation.java:210)
	at com.android.commands.monkey.x.<init>(SourceFile:2265)
	at com.android.commands.monkey.Monkey.a(SourceFile:801)
	at com.android.commands.monkey.Monkey.main(SourceFile:458)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:451)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accessibility.UiAutomationManager.registerUiTestAutomationServiceLocked(UiAutomationManager.java:88)
	at com.android.server.accessibility.AccessibilityManagerService.registerUiTestAutomationService(AccessibilityManagerService.java:801)
	at android.view.accessibility.IAccessibilityManager$Stub.onTransact(IAccessibilityManager.java:159)
	at android.os.Binder.execTransact(Binder.java:750)

[Fastbot][2022-06-30 18:31:48.687] Please report this bug issue to github

**Comment by Kim-LL** [comment]
其他程序占用了，开UI测试的东西或者启动桌面监控手机页面的东西都有可能发生这个错误，我之前启动了一个UI2，然后又运行fastbot 就是报的这个错误

**Comment by zhangzhao4444** [comment]
android系统限制，accessibilityservice只能有一个占用，关闭u2等自动化框架就可以了
