### ISSUE TITLE
测试动作为什么那么单一，没有覆盖测试的感觉

### ISSUE THREAD

**Issue by J-a-g** [bytedance/Fastbot_Android#181]
我通过白名单限制在一个Activity的场景中测试，这个Activity中有两个Fragment，通过左右滑动切换，但是每次执行测试的时候都会左滑后一直在一个Fragment里面，另外一个Fragment都测试不到，而且也没有随机动作，就是不停的重复home键且后台在返回后台，这种情况一般可能是什么原因导致

**Comment by J-a-g** [comment]
知道为什么滑倒左边fragment后无法，右滑到另一个fragment上了，原因是左边的fragment中间有一个大的按钮，滑动的动作都是从中间开始，导致滑动动作和点击冲突而失效，也就是右滑的动作失效了

**Comment by Lemon1013** [comment]
哈喽，想问一下你白名单怎么配置的，我配置的没有用

**Comment by gradient30** [comment]
> 哈喽，想问一下你白名单怎么配置的，我配置的没有用

实测只会跑一次，后边就开始各种页面随机了。- -

**Comment by zhangzhao4444** [comment]
hi，j-a-g 这个情况，可能是非标准h5页面？ 并没有获取到当前页面的  guitree，所以会一直兜底执行 home
hi，other，白名单是指将测试限制在指定的 activity 中，并非直接跳到指定配置的 activity

**Comment by zhangzhao4444** [comment]
对于自研发的 webview 控件，目前我们方法是开发一套可插桩的stub脚本集成在被app侧来获取guitree结构

**Comment by wangguoqiang1** [comment]
> 对于自研发的 webview 控件，目前我们方法是开发一套可插桩的stub脚本集成在被app侧来获取guitree结构

大佬有没有方案简单说一下呢，chrome获取dom结构太麻烦了
