### ISSUE TITLE
pixel 5， Android 13 beta 3手机上启动报错

### ISSUE THREAD

**Issue by Jerrywang77** [bytedance/Fastbot_Android#182]
在pixel 5 Android 13 beta 3手机上启动报错
![image](https://user-images.githubusercontent.com/41882120/182144718-fffa2b4d-83a4-4ce4-889b-95ddaca46610.png)

**Comment by wangchy0927** [comment]
预计啥时候支持呢，公司开始大批量适配13了

**Comment by lixf6** [comment]
+1，求适配

**Comment by zhangzhao4444** [comment]
已修改，近期发布，请关注 2.2.03.0313.1705-git monkeyq版本
