### ISSUE TITLE
在max.config中配置了max.doMutationWifiFuzzing = 0并锁定了通知栏，仍会关闭WIFI开关

### ISSUE THREAD

**Issue by hulaogou** [bytedance/Fastbot_Android#183]
![image](https://user-images.githubusercontent.com/54499036/182557674-14307cca-24ed-4c4b-a782-7dfd8422f3db.png)
之前几个月都没异常  这几天突然就有问题了

**Comment by lixf6** [comment]
求解释+1

**Comment by geron-cn** [comment]
机型和系统版本是多少呢， 麻烦提供下完整的 logcat 用于排查下问题

**Comment by zhangzhao4444** [comment]
没有更新信息，暂时先close
