### ISSUE TITLE
红米和三星设备上发生了ANR之后不会生成oom-traces.log文件

### ISSUE THREAD

**Issue by hulaogou** [bytedance/Fastbot_Android#184]
使用fastbot_Android一年了，遇到过很多次ANR，都只在crash-dump.log文件里有相关的堆栈信息。从来没生成过oom-traces.log文件

**Comment by xiaohengdai** [comment]
+1

**Comment by gradient30** [comment]
fastbot感觉自身bug挺多的- -。

**Comment by zhangzhao4444** [comment]
接入手册中有提到的，部分厂商会修改底层系统，oom-traces 存在抓取失败的情况，
