### ISSUE TITLE
催更一年了，monkey.jar该开源了吧

### ISSUE THREAD

**Issue by EdwardCheck** [bytedance/Fastbot_Android#185]
学习学习，怎么运用算法来做看上去智能的monkey测试，何时能开源核心源码

**Comment by zhangzhao4444** [comment]
内部正在重写中，monkey.jar预计会先开放源码

**Comment by EdwardCheck** [comment]
> 内部正在重写中，monkey.jar预计会先开放源码

monkey可以开源吗
