### ISSUE TITLE
黑名单中配置bounds报错

### ISSUE THREAD

**Issue by zhangkeliang2020** [bytedance/Fastbot_Android#19]
max.widget.black配置如下：
[
{
    "activity":"com.xier.bckid.main.MainActivity",
    "xpath": "//*[@text='设置']"
},
{
    "xpath": "//*[@resource-id='com.xier.bckid:id/ivDebug']"
},
{
    "activity":"com.xier.bckid.main.MainActivity",
    "xpath": "//*[@text='在线客服']"
},
{
    "activity":"com.xier.mine.message.group.MsgGroupActivity",
    "xpath": "//*[@text='在线客服']"
},
{
    "activity":"com.xier.shop.goodsdetail.GoodsDetailActivity",
    "xpath": "//*[@resource-id='com.xier.bckid:id/llCustomerService']",
    "bounds":"[156,2190][276,2340]"
}
]

运行命令如下：
adb -s RPG0219720008849 shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.xier.bckid --agent robot --running-minutes 60 --throttle 500 -v -v --bugreport --output-directory /sdcard/fastbotlog

运行启动报错：
![image](https://user-images.githubusercontent.com/43244012/104403548-b6c74c00-5593-11eb-930d-decce5748e63.png)

请大佬帮忙看看是啥问题？

**Comment by zhangzhao4444** [comment]
配置格式错误，请检查符号？

**Comment by sadmenmen** [comment]
> 配置格式错误，请检查符号？

这个bounds 格式应该怎么写，我试了好几种，都不行，文档里面也没有找到有效得资料。他这个错误和我遇到得一样，就是bounds格式不对    文件里面自动把 “  ， ”这个当作切割符了。

**Comment by geron-cn** [comment]
> > 配置格式错误，请检查符号？
> 
> 这个bounds 格式应该怎么写，我试了好几种，都不行，文档里面也没有找到有效得资料。他这个错误和我遇到得一样，就是bounds格式不对 文件里面自动把 “ ， ”这个当作切割符了。

bounds 是 , 分割的四个浮点数，你这应该改为 ：
{
"activity":"com.xier.shop.goodsdetail.GoodsDetailActivity",
"xpath": "//*[@resource-id='com.xier.bckid:id/llCustomerService']",
"bounds":"0.1,0.8,0.2,0.9"
}
