### ISSUE TITLE
定义的事件里只有点击和滑动，但执行后什么事件都有，怎么设置才能只跑点击和滑动事件呢？

### ISSUE THREAD

**Issue by s022232** [bytedance/Fastbot_Android#191]
我的脚本是这么写的：
for /f "skip=1" %%n in ('adb devices^|findstr device') do (
start /b adb -s %%n shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p %package% --agent robot --pct-motion 1 --pct-touch 99 --act-blacklist-file /sdcard/abl.strings --running-minutes %times% --throttle %throttle% -v -v -v --bugreport --output-directory /sdcard/rtcsdkCrash/
)
目的就是想只跑点击和很少部分的滑动操作，但执行后发现根本不是这么回事，怎么修改才能满足我的需求呢

**Comment by zhangzhao4444** [comment]
fastbot 不支持--pct-motion 1 --pct-touch 99  原monkey事件比例的配置
