### ISSUE TITLE
output对应目录下生成的测试报告打不开

### ISSUE THREAD

**Issue by chenweiwei** [bytedance/Fastbot_Android#192]
打开index.html，页面显示空白
![image](https://user-images.githubusercontent.com/4162920/195606482-d57e7629-f08c-47d4-b475-d1b7e7b2fcc0.png)
浏览器窗口报错

![2](https://user-images.githubusercontent.com/4162920/195614274-16ea7b10-a01a-469c-95b7-ac98a1a107bf.png)

**Comment by zhangzhao4444** [comment]
这个是遍历后的模型可视化。feature在开源上没有开放，后续看看计划
