### ISSUE TITLE
测试不到指定的测试时长就退出了

### ISSUE THREAD

**Issue by NasdaqGodzilla** [bytedance/Fastbot_Android#193]
- 通过参数指定的测试时长似乎不能正常工作
- 提前退出导致测试覆盖率不足

**Comment by NasdaqGodzilla** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/26323326/195771440-b316ef72-72eb-4951-80a9-164c088b3a30.png">

**Comment by NasdaqGodzilla** [comment]
每次执行到716时就会停止执行并退出
![Uploading image.png…]()

**Comment by zhangzhao4444** [comment]
这个看是崩溃了，也有其他人提过同样问题，请联系下qq 77227005

**Comment by NasdaqGodzilla** [comment]
看Monkey源码是Monkey内部断言崩溃，修改源码规避掉了
