### ISSUE TITLE
被测App被Fastbot停止

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [bytedance/Fastbot_Android#196]
初次使用Fastbot，发现过程中被测App被Fastbot停止（日志中的包名被XXXXXXXX替换了）。看日志Fastbot执行了RESTART操作，将App停止，请问这个怎么去掉？我还以为被测App出Bug。我执行第二遍时没有出现App被停止的情况。
10-22 11:15:08.160: I/[Fastbot](3262): // Eventid: 1611
10-22 11:15:08.163: I/[Fastbot](3262): Checked a block state g0s9
10-22 11:15:08.163: I/[Fastbot](3262): selected aciton {id: g0a0, act: RESTART, value: 0}
10-22 11:15:08.163: I/[Fastbot](3262): build state cost: 0.000s action cost: 0.000s total cost 0.001s
10-22 11:15:08.165: I/[Fastbot](3262): action type: RESTART
10-22 11:15:08.166: I/[Fastbot](3262): rpc cost time: 4
10-22 11:15:08.170: I/[Fastbot](3262): Stop all packages, retry count 9
10-22 11:15:08.171: I/[Fastbot](3262): Try to stop package com.XXXXXXXX
10-22 11:15:08.173: I/ActivityManager(427): Force stopping com.XXXXXXXX appid=10104 user=0: from pid 3262
10-22 11:15:08.175: I/ActivityManager(427): Killing 1093:com.XXXXXXXX/u0a104 (adj 0): stop com.XXXXXXXX due to from pid 3262

**Comment by zhangzhao4444** [comment]
这个是正常的restart，当遍历路径出现死胡同时，会走一些兜底
