### ISSUE TITLE
被测APP每个页面都有同一个控件，都是不同的activity，请问怎么把加入黑控件中

### ISSUE THREAD

**Issue by xsbai3009** [bytedance/Fastbot_Android#197]
被测APP每个页面都有同一个控件，都是不同的activity，请问怎么把加入黑控件中

**Comment by zhangzhao4444** [comment]
可通过max.tree.pruning配置来对特定的控件进行裁剪

**Comment by zhousijia** [comment]
> 可通过max.tree.pruning配置来对特定的控件进行裁剪

请问如何配置该文件，从文件示例来看貌似还是按单个activity来配置
![image](https://github.com/bytedance/Fastbot_Android/assets/35130692/e1e9cac0-cff4-4354-9bbe-9add95ce729b)
