### ISSUE TITLE
执行一段时间后为什么老是发送KEYCODE_BACK退出指令啊

### ISSUE THREAD

**Issue by tinysheepyang** [bytedance/Fastbot_Android#198]
[Fastbot][2022-10-31 18:53:23.045] :Sending Key (ACTION_DOWN): 4    // KEYCODE_BACK
[Fastbot][2022-10-31 18:53:23.050] :Sending Key (ACTION_UP): 4    // KEYCODE_BACK
[Fastbot][2022-10-31 18:53:23.054] Sleeping for 500 milliseconds
[Fastbot][2022-10-31 18:53:23.571] // Eventid: 42141
[Fastbot][2022-10-31 18:53:23.580] action type: BACK
[Fastbot][2022-10-31 18:53:23.580] rpc cost time: 5
[Fastbot][2022-10-31 18:53:23.637]  event time:79
[Fastbot][2022-10-31 18:53:23.638] :Sending rotation degree=0, persist=false
[Fastbot][2022-10-31 18:53:23.667] :Sending Key (ACTION_DOWN): 4    // KEYCODE_BACK
[Fastbot][2022-10-31 18:53:23.675] :Sending Key (ACTION_UP): 4    // KEYCODE_BACK
[Fastbot][2022-10-31 18:53:23.697] Sleeping for 500 milliseconds
[Fastbot][2022-10-31 18:53:24.219] // Eventid: 42145
[Fastbot][2022-10-31 18:53:24.222] action type: BACK
[Fastbot][2022-10-31 18:53:24.223] rpc cost time: 3
[Fastbot][2022-10-31 18:53:24.276]  event time:68
[Fastbot][2022-10-31 18:53:24.277] :Sending rotation degree=0, persist=false
[Fastbot][2022-10-31 18:53:24.306] :Sending Key (ACTION_DOWN): 4    // KEYCODE_BACK
[Fastbot][2022-10-31 18:53:24.311] :Sending Key (ACTION_UP): 4    // KEYCODE_BACK
[Fastbot][2022-10-31 18:53:24.315] Sleeping for 500 milliseconds
[Fastbot][2022-10-31 18:53:24.819] // the top activity is com.huawei.android.launcher.unihome.UniHomeLauncher, not testing app, need inject restart app
[Fastbot][2022-10-31 18:53:24.820] Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.xxxxxxx.internalapp/com.github.moduth.blockcanary.ui.DisplayActivity;end
[Fastbot][2022-10-31 18:53:24.829] // the top activity is com.github.moduth.blockcanary.ui.DisplayActivity, phone capture activity is com.huawei.camera.ThirdCamera
[Fastbot][2022-10-31 18:53:24.830] // Activity: com.github.moduth.blockcanary.ui.DisplayActivity in Intent
[Fastbot][2022-10-31 18:53:24.830]     // Rejecting start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.xxxxxx.internalapp/com.github.moduth.blockcanary.ui.DisplayActivity } in package com.xxxxxx.internalapp
[Fastbot][2022-10-31 18:53:24.834] Sleeping for 6000 milliseconds
[Fastbot][2022-10-31 18:53:30.858] // Eventid: 42151
[Fastbot][2022-10-31 18:53:30.862] action type: BACK
[Fastbot][2022-10-31 18:53:30.863] rpc cost time: 3
[Fastbot][2022-10-31 18:53:30.924]  event time:83
[Fastbot][2022-10-31 18:53:30.925] :Sending rotation degree=0, persist=false
[Fastbot][2022-10-31 18:53:30.956] :Sending Key (ACTION_DOWN): 4    // KEYCODE_BACK
[Fastbot][2022-10-31 18:53:30.961] :Sending Key (ACTION_UP): 4    // KEYCODE_BACK
[Fastbot][2022-10-31 18:53:30.966] Sleeping for 500 milliseconds

**Comment by gradient30** [comment]
> [Fastbot][2022-10-31 18:53:23.045] :Sending Key (ACTION_DOWN): 4 // KEYCODE_BACK [Fastbot][2022-10-31 18:53:23.050] :Sending Key (ACTION_UP): 4 // KEYCODE_BACK [Fastbot][2022-10-31 18:53:23.054] Sleeping for 500 milliseconds [Fastbot][2022-10-31 18:53:23.571] // Eventid: 42141 [Fastbot][2022-10-31 18:53:23.580] action type: BACK [Fastbot][2022-10-31 18:53:23.580] rpc cost time: 5 [Fastbot][2022-10-31 18:53:23.637] event time:79 [Fastbot][2022-10-31 18:53:23.638] :Sending rotation degree=0, persist=false [Fastbot][2022-10-31 18:53:23.667] :Sending Key (ACTION_DOWN): 4 // KEYCODE_BACK [Fastbot][2022-10-31 18:53:23.675] :Sending Key (ACTION_UP): 4 // KEYCODE_BACK [Fastbot][2022-10-31 18:53:23.697] Sleeping for 500 milliseconds [Fastbot][2022-10-31 18:53:24.219] // Eventid: 42145 [Fastbot][2022-10-31 18:53:24.222] action type: BACK [Fastbot][2022-10-31 18:53:24.223] rpc cost time: 3 [Fastbot][2022-10-31 18:53:24.276] event time:68 [Fastbot][2022-10-31 18:53:24.277] :Sending rotation degree=0, persist=false [Fastbot][2022-10-31 18:53:24.306] :Sending Key (ACTION_DOWN): 4 // KEYCODE_BACK [Fastbot][2022-10-31 18:53:24.311] :Sending Key (ACTION_UP): 4 // KEYCODE_BACK [Fastbot][2022-10-31 18:53:24.315] Sleeping for 500 milliseconds [Fastbot][2022-10-31 18:53:24.819] // the top activity is com.huawei.android.launcher.unihome.UniHomeLauncher, not testing app, need inject restart app [Fastbot][2022-10-31 18:53:24.820] Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.xxxxxxx.internalapp/com.github.moduth.blockcanary.ui.DisplayActivity;end [Fastbot][2022-10-31 18:53:24.829] // the top activity is com.github.moduth.blockcanary.ui.DisplayActivity, phone capture activity is com.huawei.camera.ThirdCamera [Fastbot][2022-10-31 18:53:24.830] // Activity: com.github.moduth.blockcanary.ui.DisplayActivity in Intent [Fastbot][2022-10-31 18:53:24.830] // Rejecting start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.xxxxxx.internalapp/com.github.moduth.blockcanary.ui.DisplayActivity } in package com.xxxxxx.internalapp [Fastbot][2022-10-31 18:53:24.834] Sleeping for 6000 milliseconds [Fastbot][2022-10-31 18:53:30.858] // Eventid: 42151 [Fastbot][2022-10-31 18:53:30.862] action type: BACK [Fastbot][2022-10-31 18:53:30.863] rpc cost time: 3 [Fastbot][2022-10-31 18:53:30.924] event time:83 [Fastbot][2022-10-31 18:53:30.925] :Sending rotation degree=0, persist=false [Fastbot][2022-10-31 18:53:30.956] :Sending Key (ACTION_DOWN): 4 // KEYCODE_BACK [Fastbot][2022-10-31 18:53:30.961] :Sending Key (ACTION_UP): 4 // KEYCODE_BACK [Fastbot][2022-10-31 18:53:30.966] Sleeping for 500 milliseconds

试试max.config里配置Fuzz对应事件的概率，max.doSystemKeyFuzzing = 0
