### ISSUE TITLE
如何屏蔽某些操作，例如不想触发BACK

### ISSUE THREAD

**Issue by potter444** [bytedance/Fastbot_Android#199]
现在测试app的小程序，BACK会直接关闭小程序，就想屏蔽这个指令

**Comment by gradient30** [comment]
> 现在测试app的小程序，BACK会直接关闭小程序，就想屏蔽这个指令

max.config里配置Fuzz对应事件的概率，max.doSystemKeyFuzzing = 0

**Comment by zhangzhao4444** [comment]
back并非systemkey，这种情况只能在退出后的页面中配置自定义事件进行再次进入测试内容

**Comment by littlejlf** [comment]
> 现在测试app的小程序，BACK会直接关闭小程序，就想屏蔽这个指令

兄弟你有解决吗 我现在也想测试小程序
