### ISSUE TITLE
--agent reuseq 和--agent robot 有什么区别么

### ISSUE THREAD

**Issue by ligho** [bytedance/Fastbot_Android#207]
--agent reuseq 和--agent robot 有什么区别么

**Comment by wangxa97** [comment]
根据我遇到的问题 -agent reuseq应该就是以复用之前模型的模式启动 -agent rebot 就是重新训练一个新模型

**Comment by zhangzhao4444** [comment]
reuseq： 基于模型的强化学习算法

其他参数（包括rebot）：走的都是reuseq，其他算法目前都没有reuseq效果好，所以去掉了
