### ISSUE TITLE
启动 fastbot 加载模型时报 loadReuseModel 异常

### ISSUE THREAD

**Issue by wangxa97** [bytedance/Fastbot_Android#211]
现象：[Fastbot][2023-02-06 17:07:38.786] fastbot native : library load!
出现该句后直接闪退
解决方案：删除该应用保存的.fbm文件。
根因：#00 pc 00000000000f43b0  /data/local/tmp/arm64-v8a/libfastbot_native.so (fastbotx::ReuseAgent::loadReuseModel(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >)+852) (BuildId: 36c6b9e10b75e6ecdb7e69cfcc10d16d4ccd5ad2)
可以看到是重新加载模型时报错，所以猜测-agent reuseq应该就是以复用之前模型的模式启动 -agent rebot 就是重新训练一个新模型

**Comment by zhangzhao4444** [comment]
呃，fbm模型像是损坏了，load报错

**Comment by zhangzhao4444** [comment]
尝试删除fbm文件看能否解决

**Comment by lk236225128** [comment]
删除fbm文件后，再次运行似乎再也没生成fbm文件了，请问一下，我想持续训练模型该如何解决

**Comment by zhangzhao4444** [comment]
> 删除fbm文件后，再次运行似乎再也没生成fbm文件了，请问一下，我想持续训练模型该如何解决
fbm 不存在时，应该会重新生成的，每次运行fastbot这个fbm文件会迭代更新
