### ISSUE TITLE
max.widget.black max.tree.pruning不生效

### ISSUE THREAD

**Issue by wangxa97** [bytedance/Fastbot_Android#212]
行 67900: 02-07 21:29:53.933 15205 15205 I [Fastbot]: pruning node com.tencent.mobileqq:id/qj6 for xpath: //*[@resource-id='com.tencent.mobileqq:id/qj6' and content-desc='添加帐号']
	行 67902: 02-07 21:29:53.933 15205 15205 I [Fastbot]: pruning node com.tencent.mobileqq:id/dv8 for xpath: //*[@resource-id='com.tencent.mobileqq:id/dv8' and content-desc='退出当前帐号']
	行 67903: 02-07 21:29:53.937 15205 15205 I [Fastbot]: select action not in reuse model
	行 67904: 02-07 21:29:53.937 15205 15205 I [Fastbot]: total visited activity count is 3
	行 67905: 02-07 21:29:53.938 15205 15205 I [Fastbot]: selected aciton {{id: g0a40, act: CLICK, value: 0}, state: , node: {xpath: /*[@class="android.widget.ImageView"][@resource-id="com.tencent.mobileqq:id/qj6"][@text=""][@content-desc="添加帐号"][@index=4][@bounds="[670,1914][800,2044]"]}}
	行 67906: 02-07 21:29:53.938 15205 15205 I [Fastbot]: build state cost: 0.005s action cost: 0.001s total cost 0.006s
	行 67908: 02-07 21:29:53.942 15205 15205 I [Fastbot]: action type: CLICK
	行 67909: 02-07 21:29:53.944 15205 15205 I [Fastbot]: rpc cost time: 38
	行 67915: 02-07 21:29:53.971 15205 15205 I [Fastbot]: check point [729, 2037] is not in black widgets
已经将添加帐号的node裁剪掉还是点击了

**Comment by wangxa97** [comment]
行 97517: 02-07 22:01:12.341 25577 25577 I [Fastbot]: // Eventid: 624
	行 97592: 02-07 22:01:12.539 25577 25577 I [Fastbot]: black widget xpath //*[@resource-id='com.tencent.mobileqq:id/qj6' and content-desc='添加帐号'], has no bounds matched 1 nodes
	行 97593: 02-07 22:01:12.539 25577 25577 I [Fastbot]: black wdiget, delete node: com.tencent.mobileqq:id/qj6 depends xpath
	行 97594: 02-07 22:01:12.539 25577 25577 I [Fastbot]: black widget xpath //*[@resource-id='com.tencent.mobileqq:id/dv8' and content-desc='退出当前帐号'], has no bounds matched 1 nodes
	行 97595: 02-07 22:01:12.539 25577 25577 I [Fastbot]: black wdiget, delete node: com.tencent.mobileqq:id/dv8 depends xpath
	行 97596: 02-07 22:01:12.540 25577 25577 I [Fastbot]: select action in reuse model
	行 97597: 02-07 22:01:12.540 25577 25577 I [Fastbot]: total visited activity count is 2
	行 97598: 02-07 22:01:12.540 25577 25577 I [Fastbot]: selected aciton {{id: g0a2, act: CLICK, value: 0}, state: , node: {xpath: /*[@class="android.widget.FrameLayout"][@resource-id=""][@text=""][@content-desc=""][@index=2][@bounds="[856,115][953,218]"]}}
	行 97599: 02-07 22:01:12.540 25577 25577 I [Fastbot]: build state cost: 0.001s action cost: 0.000s total cost 0.001s
	行 97600: 02-07 22:01:12.541 25577 25577 I [Fastbot]: action type: CLICK
	行 97602: 02-07 22:01:12.542 25577 25577 I [Fastbot]: rpc cost time: 4
	行 97607: 02-07 22:01:12.559 25577 25577 I [Fastbot]: check point [910, 180] is  in black widgets
	行 97608: 02-07 22:01:12.559 25577 25577 I [Fastbot]: check point [23, 357] is  in black widgets
	行 97609: 02-07 22:01:12.559 25577 25577 I [Fastbot]: check point [753, 1611] is  in black widgets
	行 97610: 02-07 22:01:12.559 25577 25577 I [Fastbot]: check point [683, 1959] is  in black widgets
	行 97611: 02-07 22:01:12.559 25577 25577 I [Fastbot]: check point [125, 1854] is  in black widgets
	行 97612: 02-07 22:01:12.559 25577 25577 I [Fastbot]: check point [1005, 1122] is  in black widgets
	行 97613: 02-07 22:01:12.559 25577 25577 I [Fastbot]: check point [1070, 2073] is  in black widgets
	行 97614: 02-07 22:01:12.559 25577 25577 I [Fastbot]: check point [741, 519] is  in black widgets
	行 97615: 02-07 22:01:12.559 25577 25577 I [Fastbot]: check point [347, 1491] is  in black widgets
	行 97616: 02-07 22:01:12.559 25577 25577 I [Fastbot]: check point [347, 714] is  in black widgets
	行 97617: 02-07 22:01:12.559 25577 25577 I [Fastbot]: check point [691, 2010] is  in black widgets
	行 97618: 02-07 22:01:12.560 25577 25577 W [Fastbot]: *** WARNING *** %scheckVirtualKeyboard: Input only once.
	行 97619: 02-07 22:01:12.562 25577 25577 I [Fastbot]:  event time:225
	行 97620: 02-07 22:01:12.563 25577 25577 I [Fastbot]: :Sending rotation degree=0, persist=false
	行 97675: 02-07 22:01:12.588 25577 25577 I [Fastbot]: :Sending Touch (ACTION_DOWN): 0:(691.2987,2010.0)
	行 97699: 02-07 22:01:12.596 25577 25577 I [Fastbot]: :Sending Touch (ACTION_UP): 0:(691.2987,2010.0)
max.widget.black也不生效。 check point [347, 714] is  in black widgets很多都是错误的并不在黑控件的区域内，反而是最后选择的坐标(691.2987,2010.0)处于黑控件中

**Comment by zhangzhao4444** [comment]
控件屏蔽后续重构下，排除下该问题

**Comment by synioe** [comment]
> 
同样的max.widget.balck屏蔽控件不生效问题，请问是否fix了？另外是否会考虑源码也开源？

**Comment by zhangzhao4444** [comment]
2.3.23.0810.1705-git fixed
