### ISSUE TITLE
现在的版本怎么老是触到wifi关闭无线，1.0时代没遇到过

### ISSUE THREAD

**Issue by ceshi2018** [bytedance/Fastbot_Android#216]
最新版试了一下，老是触到wifi关掉，
1.0时代没遇到过
有什么需要特殊设置吗

**Comment by zhangzhao4444** [comment]
可参考中文手册中

**Comment by zhangzhao4444** [comment]
增加Fuzz和mutation event 【new】
模型推理执行某个action后按fuzzingrate几率生成5-10个fuzz序列，由如下event乱序组合

在PC端新建 max.config文件
增加以下参数
max.fuzzingRate = 0.01D //0.01为Fuzz事件的总概率
fuzzingRate包含的事件(数字为默认概率):
max.doRotateFuzzing = 0.15
max.doAppSwitchFuzzing = 0.15
max.doTrackballFuzzing = 0.15
max.doNavKeyFuzzing = 0.15
max.doKeyCodeFuzzing = 0.15
max.doSystemKeyFuzzing = 0.15
max.doDragFuzzing = 0.5
max.doPinchZoomFuzzing = 0.15 
max.doClickFuzzing = 0.7
max.startMutation = 0.3D //启动Fastbot立刻设置mutation的几率，默认30%
fuzzingRate包含的事件(数字为默认概率，此概率为事件总概率):
max.doMutationAirplaneFuzzing = 0.001
max.doMutationMutationAlwaysFinishActivitysFuzzing = 0.1
max.doMutationWifiFuzzing = 0.001
飞行模式、wifi开关这两个在Fastbot执行完会重置开启
将 max.config 文件push到手机端sdcard中，目录必须为sdcard
adb push max.config /sdcard
