### ISSUE TITLE
跑完fastbot，后面正常迭代app版本，发现无法进某个页面，出现app重启

### ISSUE THREAD

**Issue by G-chunyang** [bytedance/Fastbot_Android#218]
排查了不是app本身问题，只有跑了fastbot的手机出现了重启，麻烦帮分析一下😂，我把fastbot相关文件都删除了，app也重装都不能解决这个问题。
[app重启日志.txt](https://github.com/bytedance/Fastbot_Android/files/11120696/app.txt)

https://user-images.githubusercontent.com/48399416/229091233-8d2e85fc-21c3-46dc-b8a6-7e1ed2cb5db6.mp4

[fastbot配置文件.zip](https://github.com/bytedance/Fastbot_Android/files/11120704/fastbot.zip)

**Comment by zhangzhao4444** [comment]
这个应用是原生Android应用吗？

**Comment by G-chunyang** [comment]
应该是吧，不是很了解

**Comment by zhangzhao4444** [comment]
log中没有找到fastbot
