### ISSUE TITLE
OPPO设备，运行SHELL_EVENT事件失败

### ISSUE THREAD

**Issue by Enerwen** [bytedance/Fastbot_Android#219]
已经开启 禁止权限监控

max.xpath.actions 配置文件：
[
    {
        "prob": 1,
        "activity": "com.android.launcher.Launcher",
        "times": 1,
        "actions": [
            {
                "action": "SHELL_EVENT",
                "command": "input keyevent 82",
                "wait": 10000,
                "throttle": 1000
            },
            {
                "action": "SHELL_EVENT",
                "command": "input keyevent 82",
                "wait": 10000,
                "throttle": 1000
            },
            {
                "action": "SHELL_EVENT",
                "command": "input keyevent 26",
                "wait": 10000,
                "throttle": 1000
            },
            {
                "action": "SHELL_EVENT",
                "command": "input keyevent 26",
                "wait": 10000,
                "throttle": 1000
            }
        ]
    }
]

执行时报错日志：
[Fastbot][2023-04-12 10:28:37.473] // current activity is com.android.launcher.Launcher
[Fastbot][2023-04-12 10:28:37.482] // Eventid: 1
[Fastbot][2023-04-12 10:28:37.529] action type: SHELL_EVENT
[Fastbot][2023-04-12 10:28:37.531] rpc cost time: 19
[Fastbot][2023-04-12 10:28:37.547]  event time:72
[Fastbot][2023-04-12 10:28:37.548] :Sending rotation degree=0, persist=false
**[Fastbot][2023-04-12 10:28:37.582]     // Injection Failed com.android.commands.monkey.f@d34a49a**
[Fastbot][2023-04-12 10:28:37.586] Sleeping for 3500 milliseconds
[Fastbot][2023-04-12 10:28:41.096] Sleeping for 3500 milliseconds
[Fastbot][2023-04-12 10:28:44.616] // Eventid: 5
[Fastbot][2023-04-12 10:28:44.631] action type: SHELL_EVENT
[Fastbot][2023-04-12 10:28:44.633] rpc cost time: 5
[Fastbot][2023-04-12 10:28:44.639]  event time:31
[Fastbot][2023-04-12 10:28:44.640] :Sending rotation degree=0, persist=false
**[Fastbot][2023-04-12 10:28:44.676]     // Injection Failed com.android.commands.monkey.f@2ad31cb**
[Fastbot][2023-04-12 10:28:44.679] Sleeping for 3500 milliseconds
[Fastbot][2023-04-12 10:28:48.189] Sleeping for 3500 milliseconds
[Fastbot][2023-04-12 10:28:51.706] // Eventid: 9
[Fastbot][2023-04-12 10:28:51.720] action type: SHELL_EVENT
[Fastbot][2023-04-12 10:28:51.722] rpc cost time: 7
[Fastbot][2023-04-12 10:28:51.729]  event time:30
[Fastbot][2023-04-12 10:28:51.730] :Sending rotation degree=0, persist=false
[Fastbot][2023-04-12 10:28:51.765]     // Injection Failed com.android.commands.monkey.f@6ec3da8
[Fastbot][2023-04-12 10:28:51.768] Sleeping for 3500 milliseconds
[Fastbot][2023-04-12 10:28:55.279] Sleeping for 3500 milliseconds
[Fastbot][2023-04-12 10:28:58.798] // Eventid: 13
[Fastbot][2023-04-12 10:28:58.812] action type: SHELL_EVENT
[Fastbot][2023-04-12 10:28:58.814] rpc cost time: 7
[Fastbot][2023-04-12 10:28:58.820]  event time:30
[Fastbot][2023-04-12 10:28:58.821] :Sending rotation degree=0, persist=false
[Fastbot][2023-04-12 10:28:58.859]     // Injection Failed com.android.commands.monkey.f@54fa0c1
[Fastbot][2023-04-12 10:28:58.863] Sleeping for 3500 milliseconds

**Comment by zhangzhao4444** [comment]
[Fastbot][2023-04-12 10:28:37.582] // Injection Failed com.android.commands.monkey.f@d34a49a
看log似乎系统服务异常了，只能重启下设备
