### ISSUE TITLE
运行遍历后，未生成/sdcard/fastbot_[packagename].fbm文件

### ISSUE THREAD

**Issue by lk236225128** [bytedance/Fastbot_Android#221]
你好，我运行遍历后，未生成/sdcard/fastbot_[packagename].fbm文件。
执行命令为`adb -s J5AZB760T547H5K shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.xxxx.xxxx --agent reuseq --act-blacklist-file /sdcard/abl.strings --bugreport --output-directory /sdcard/20230417.log --running-minutes 40 --throttle 500 -v -v`。
遍历执行完后，没有生成.fbm文件，把--agent 改为robot也没有生成.fbm。我想复用或训练模型，请问该如何操作？
执行结束后的目录文件如下图：
![image](https://user-images.githubusercontent.com/43338050/232455418-da32afd7-f303-43c6-a1f4-f9e044ff1e07.png)

**Comment by 2911236097** [comment]
[monkeyq.jar](https://github.com/bytedance/Fastbot_Android/blob/main/monkeyq.jar)
[fix android13](https://github.com/bytedance/Fastbot_Android/commit/d3df7a53f6fccecffcad481618d24ca958ff5c5e)

用这个fix android13的monkeyq.jar可以生成fbm,用旧版的不会.
但是这个新的monkeyq.jar也有bug,执行不了自定义事件.

**Comment by zhangzhao4444** [comment]
自定义事件正在修改了，得等下个版本fix

**Comment by zhangzhao4444** [comment]
2.3.23.0810.1705-git fixed
