### ISSUE TITLE
对于空白页面或者toast提示出的错误，有断言或者捕获的方式么？

### ISSUE THREAD

**Issue by ljqaqq** [bytedance/Fastbot_Android#225]
请问，如题，当页面出现了空白页面，或者toast提示了服务器异常加载异常之类的场景，是否有断言的方式？

**Comment by ljqaqq** [comment]
还有一个问题需要请教，想实现点指定页面的指定按钮，现在设置了abl.strings和max.xpath.actions,还是会出现乱点的情况，不去点指定的activity的指定xpath对应的按钮，甚至运行到最后都不点击设置的action，请问这个是哪里有问题么？

**Comment by ljqaqq** [comment]
![image](https://github.com/bytedance/Fastbot_Android/assets/7824863/2f095b82-1c4f-46e7-8e3b-1d29dc49fd06)
![image](https://github.com/bytedance/Fastbot_Android/assets/7824863/abbaced0-4201-4491-8372-e4e289877937)

**Comment by gradient30** [comment]
放弃吧，这个开源bug多得离谱- - 作者完全没时间解决了。

**Comment by zhangzhao4444** [comment]
目前没有这个机制，
