### ISSUE TITLE
不加--bugreport参数， 跑完 /sdcard/crash_dump.log 文件消失，有删除逻辑吗？

### ISSUE THREAD

**Issue by superWenshuo** [bytedance/Fastbot_Android#227]
启动命令不加--bugreport 也应该在 /sdcard/crash_dump.log写入崩溃日志吧。
发现使用
adb -s QKX4C20420006320 shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.sohu.sohuvideo --agent reuseq --act-blacklist-file  /sdcard/abl.strings --running-minutes 240 --throttle 500 -v -v  
跑脚本，/sdcard/crash_dump.log 文件消失

**Comment by superWenshuo** [comment]
设备是电视剧盒子 ott设备，底层也是android，是9.0系统

**Comment by zhangzhao4444** [comment]
逻辑里没有删除 crash_dump.log的
