### ISSUE TITLE
Crash 堆栈未能写入 crash-dump.log

### ISSUE THREAD

**Issue by cheneyxwong** [bytedance/Fastbot_Android#23]
##### 现象描述
FastBot 捕获到被测 app crash 但未能写入到 /sdcard/crash-dump.log 中，尝试 pull 文件报错。
##### 日志片段
![WeCom20210115-175239](https://user-images.githubusercontent.com/14826144/104710456-13289800-575b-11eb-9c09-1d9e2b120070.png)
##### 执行环境
- Pixel 2XL, Android 11

**Comment by cheneyxwong** [comment]
Galaxy S10+, Android 10 也未能写入。

**Comment by zhangzhao4444** [comment]
输入的shell命令发我看下？

**Comment by cheneyxwong** [comment]
```
adb shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p 'com.package' --agent robot --running-minutes 15 --throttle 500 --bugreport
```

**Comment by gavin-huangwang** [comment]
android 8.1 传音手机 infinix x624 也有这个问题

**Comment by zhangzhao4444** [comment]
更新版本，再验证下
