### ISSUE TITLE
ADBKeyBoard输入配置文件中随机读取字符串输入，不生效。

### ISSUE THREAD

**Issue by NotEatSugar** [bytedance/Fastbot_Android#235]
ADBKeyBoard设置默认输入法
配置文件 max.config 中 max.randomPickFromStringList = true 
 max.strings 文件 push 到sdcard
执行测试时输入配置文件中随机读取字符串输入，不生效。

**Comment by zhangzhao4444** [comment]
2.3.23.0810.1705-git 版本已修改
