### ISSUE TITLE
A possible way to improve Activity Coverage and Code Coverage

### ISSUE THREAD

**Issue by zzzzfeng** [bytedance/Fastbot_Android#236]
If get all exposed components(Activity) from parsing AndroidManifest.xml in the apk, then start it one by one. 
It may improve Activity Coverage and Code Coverage

> _just_ as the way in https://github.com/zzzzfeng/amonkey

**Comment by zhangzhao4444** [comment]
activity start it one by one ?

**Comment by zzzzfeng** [comment]
对的，可能需要加上参数解析，才能正确启动组件
_解析参数可参考_ https://mp.weixin.qq.com/s/G77VeaKc6gFD5QKm7WQOxg
