### ISSUE TITLE
Fastbot 运行过程中因为 null pointer dereference停止

### ISSUE THREAD

**Issue by littlesunmie** [bytedance/Fastbot_Android#240]
CB4282E  08-26 12:54:50.033 16173 16173 F DEBUG   : Cmdline: com.android.commands.monkey
CB4282F  08-26 12:54:50.033 16173 16173 F DEBUG   : pid: 18175, tid: 18175, name: commands.monkey  >>> com.android.commands.monkey <<<
CB42830  08-26 12:54:50.033 16173 16173 F DEBUG   : uid: 0
CB42831  08-26 12:54:50.033 16173 16173 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
CB42832  08-26 12:54:50.033 16173 16173 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
CB42833  08-26 12:54:50.033 16173 16173 F DEBUG   : Cause: null pointer dereference
CB42834  08-26 12:54:50.033 16173 16173 F DEBUG   :     x0  0000000000000000  x1  0000000000000000  x2  00000072d65bda90  x3  0000007fd7d34a78
CB42835  08-26 12:54:50.033 16173 16173 F DEBUG   :     x4  0000000000000000  x5  00000000020959de  x6  0000000000000010  x7  7f7f7f7fffff7fff
CB42836  08-26 12:54:50.034 16173 16173 F DEBUG   :     x8  0000000000000000  x9  82a29b529b4b3174  x10 0000000000000670  x11 0000000000000005
CB42837  08-26 12:54:50.034 16173 16173 F DEBUG   :     x12 000000000000c063  x13 000000007fffffff  x14 00000000020959de  x15 000001a51047131f
CB42838  08-26 12:54:50.034 16173 16173 F DEBUG   :     x16 000000726d7e8280  x17 0000007540aa8900  x18 0000007564076000  x19 0000007fd7d34f00
CB42839  08-26 12:54:50.034 16173 16173 F DEBUG   :     x20 0000007fd7d34ee8  x21 0000007fd7d34f18  x22 b40000743654e210  x23 0000007563528000
CB4283A  08-26 12:54:50.034 16173 16173 F DEBUG   :     x24 0000000000000043  x25 b400007406591190  x26 0000000000000050  x27 0000007563528000
CB4283B  08-26 12:54:50.034 16173 16173 F DEBUG   :     x28 000000726d7ec000  x29 0000007fd7d34ea0
CB4283C  08-26 12:54:50.034 16173 16173 F DEBUG   :     lr  000000726d6d4cf4  sp  0000007fd7d34e70  pc  0000007540aa8910  pst 0000000080000000
CB4283D  08-26 12:54:50.034 16173 16173 F DEBUG   : 26 total frames
CB4283E  08-26 12:54:50.034 16173 16173 F DEBUG   : backtrace:
CB4283F  08-26 12:54:50.034 16173 16173 F DEBUG   :       #00 pc 0000000000055910  /apex/com.android.runtime/lib64/bionic/libc.so (__strlen_aarch64+16) (BuildId: cbc8037a79fa37869e148e2dc20182ec)
CB42840  08-26 12:54:50.034 16173 16173 F DEBUG   :       #01 pc 00000000000d1cf0  /data/local/tmp/arm64-v8a/libfastbot_native.so (fastbotx::Model::getOperate(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)+120) (BuildId: 36c6b9e10b75e6ecdb7e69cfcc10d16d4ccd5ad2)
CB42841  08-26 12:54:50.034 16173 16173 F DEBUG   :       #02 pc 00000000001181c8  /data/local/tmp/arm64-v8a/libfastbot_native.so (Java_com_bytedance_fastbot_AiClient_b0bhkadf+356) (BuildId: 36c6b9e10b75e6ecdb7e69cfcc10d16d4ccd5ad2)
CB42842  08-26 12:54:50.034 16173 16173 F DEBUG   :       #03 pc 000000000203a360  /memfd:jit-cache (deleted) (offset 0x2000000) (art_jni_trampoline+144)
CB42843  08-26 12:54:50.035 16173 16173 F DEBUG   :       #04 pc 0000000002018a6c  /memfd:jit-cache (deleted) (offset 0x2000000) (com.bytedance.fastbot.AiClient.l+204)
CB42844  08-26 12:54:50.035 16173 16173 F DEBUG   :       #05 pc 0000000002040404  /memfd:jit-cache (deleted) (offset 0x2000000) (com.android.commands.monkey.x.z+1844)
CB42845  08-26 12:54:50.035 16173 16173 F DEBUG   :       #06 pc 0000000002015a0c  /memfd:jit-cache (deleted) (offset 0x2000000) (com.android.commands.monkey.x.k+2060)
CB42846  08-26 12:54:50.035 16173 16173 F DEBUG   :       #07 pc 00000000020027d0  /memfd:jit-cache (deleted) (offset 0x2000000) (com.android.commands.monkey.Monkey.f+5584)
CB42847  08-26 12:54:50.035 16173 16173 F DEBUG   :       #08 pc 000000000058ac54  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: b10f5696fea1b32039b162aef3850ed3)
CB42848  08-26 12:54:50.035 16173 16173 F DEBUG   :       #09 pc 000000000000a3ea  [anon:dalvik-classes.dex extracted in memory from /storage/emulated/0/monkeyq.jar] (com.android.commands.monkey.Monkey.a+2126)

**Comment by MoveVector** [comment]
你好，我这边发现你用的是之前的so文件，请你把so文件换成新版本的试试看。
