### ISSUE TITLE
FindMethod()问题

### ISSUE THREAD

**Issue by doomedkiddo** [bytedance/Fastbot_Android#241]
adb shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey 10000
[Fastbot]*** ERROR *** findMethod() error, NoSuchMethodException happened, there is no such method: setActivityController
[Fastbot]*** WARNING *** // Warning: no activities found for category android.intent.category.MONKEY

**Comment by zhangzhao4444** [comment]
可忽略的log，对运行无影响
