### ISSUE TITLE
在OPPO Reno 8 Pro+上运行遇到错误直接退出运行了Cannot resolve method: queryIntentActivities

### ISSUE THREAD

**Issue by astrid77** [bytedance/Fastbot_Android#242]
[Fastbot][2023-09-01 10:58:19.801]  @Version: 2.2.01.1101.2108-git
[Fastbot][2023-09-01 10:58:19.823] // Monkey: seed=1693626044302 count=1000

[Fastbot][2023-09-01 10:58:19.823] // AllowPackage: ...
[Fastbot][2023-09-01 10:58:19.823] // IncludeCategory: android.intent.category.LAUNCHER
[Fastbot][2023-09-01 10:58:19.824] // IncludeCategory: android.intent.category.MONKEY
[Fastbot][2023-09-01 10:58:19.831] Cannot resolve method: queryIntentActivities

**Comment by zhangzhao4444** [comment]
更新下版本？ version 看着是很老的版本

**Comment by astrid77** [comment]
> 更新下版本？ version 看着是很老的版本

更新monkeyq.jar后解决了，多谢~

**Comment by uhyug123** [comment]
> > 更新版本？ 版本看着是很旧的版本
> 
> 更新monkeyq.jar后解决了，非常感谢~

怎么更新jar包
