### ISSUE TITLE
请问为什么配置了白名单, 还是会执行很多非白名单的activity

### ISSUE THREAD

**Issue by fengzongming** [bytedance/Fastbot_Android#33]
我的方案是: 
先进入到UserInfoActivity, 再执行monkey

但是还是执行了很多非白名单的activity, 白名单的覆盖率约为50%

在白名单配置了UserInfoActivity, 
![image](https://user-images.githubusercontent.com/40770289/109276069-86d8bd00-7850-11eb-9907-e6f5e6daadc2.png)

最后执行的activity
![image](https://user-images.githubusercontent.com/40770289/109276274-c7d0d180-7850-11eb-9fc9-48616a25ed4e.png)

**Comment by fengzongming** [comment]
@Version : 2.2.1.1222.1615_git

我看了下日志, 应该是因为没有走没有走startActivity()这个方法, 所以没有拦截吧

会有如下两种路径, 
1. 点击应用的返回键, 相当于是Activity出栈的形式切换的activity, 所以没有拦截到
![image](https://user-images.githubusercontent.com/40770289/109281198-f651ab00-7856-11eb-9fb6-900333ac17b7.png)


2. 触发了系统的返回事件, 也不会拦截activity
![image](https://user-images.githubusercontent.com/40770289/109281029-bbe80e00-7856-11eb-934f-b8130e0a6822.png)


麻烦大佬处理下这两种情况的拦截, 非常感谢

**Comment by zhangzhao4444** [comment]
同学你好，maintabactivity是app launcher或第一个main页面吗？默认情况下会把这两个也没也添加到白名单中，为了避免app崩溃因不在白名单中而造成无法启动的情况
