### ISSUE TITLE
【需求】遍历时的guitree增加dump本地化存储

### ISSUE THREAD

**Issue by windanchaos** [bytedance/Fastbot_Android#37]
想利用遍历的dom的xml做些diff工作，是否可以考虑把现在dom的xml命名规则改为
当前step + 当前 activity + 上一步所点击 的xpath + 具体操作 的形式？
不知道这种想法是不是合理，还请考虑。

**Comment by zhangzhao4444** [comment]
已实现

**Comment by DennielZhang** [comment]
请问现在dump的截图以及UI hierarchy文件的文件名应该如何理解呢？如：step-1--g0a5-1655160668573.png，可以理解第一部分指的是当前为第几个step, 请问后面部分应该对应什么？谢谢！
