### ISSUE TITLE
monkey执行完的统计结果中有anr,但/sdcard/oom-traces.log文件为空

### ISSUE THREAD

**Issue by gavin-huangwang** [bytedance/Fastbot_Android#40]
统计结果：
![1](https://user-images.githubusercontent.com/30430653/111934059-aaafbb80-8afb-11eb-931c-197b1b539019.png)
查看logcat日志，发现，跳过Skip anr dump，如下
![image](https://user-images.githubusercontent.com/30430653/111934222-f19db100-8afb-11eb-87ee-5b5275ee416e.png)

**Comment by zhangzhao4444** [comment]
存在厂商定制修改过，造成oom-traces无法获取
