### ISSUE TITLE
max.widget.black中设置的控件偶尔仍然被点击

### ISSUE THREAD

**Issue by xiaohengdai** [bytedance/Fastbot_Android#41]
![image](https://user-images.githubusercontent.com/17376841/114696342-20035a80-9d4f-11eb-8aa7-afad5411de8a.png)

max.widget.black中的内容：
[
{
    "activity":"com.yxcorp.gifshow.aggregate.AggregateActivity",
    "xpath":"//*[@resource-id='com.kuaishou.nebula:id/left_btn']"
},
{
    "activity":"com.yxcorp.gifshow.aggregate.AggregateActivity",
    "xpath":"//*[@resource-id='com.kuaishou.nebula:id/avatar']"
},
{
    "activity":"com.yxcorp.gifshow.aggregate.AggregateActivity",
    "xpath":"//*[@resource-id='com.kuaishou.nebula:id/name']"
},
{
    "activity":"com.yxcorp.gifshow.aggregate.AggregateActivity",
    "xpath":"//*[@resource-id='com.kuaishou.nebula:id/text']"
}
]

**Comment by sadmenmen** [comment]
我也发现这个问题了，然后打算加上黑区域bounds。但是规则怎么写都不对

**Comment by sadmenmen** [comment]
这样会报错
[
{
    "activity":"com.xiaomi.smarthome.SmartHomeMainActivity",
	"xpath":"//*[@resource-id='com.xiaomi.smarthome:id/ax0']/android.widget.FrameLayout[2]",
	"bounds":{'left': 216, 'top': 2178, 'right': 432, 'bottom': 2308}
}
]

**Comment by sadmenmen** [comment]
这样也会
[
{
    "activity":"com.xiaomi.smarthome.SmartHomeMainActivity",
	"xpath":"//*[@resource-id='com.xiaomi.smarthome:id/ax0']/android.widget.FrameLayout[2]",
	"bounds":"[296,2264][352,2302]"
}
]

**Comment by geron-cn** [comment]
> related: #19
