### ISSUE TITLE
max.xpath.actions中设置自定义操作实际上并没有执行

### ISSUE THREAD

**Issue by xiaohengdai** [bytedance/Fastbot_Android#42]
![image](https://user-images.githubusercontent.com/17376841/114696648-78d2f300-9d4f-11eb-8e00-064d2a64c84f.png)

**Comment by xiaohengdai** [comment]
max.xpath.actions:
[
{
    "prob": 1,
    "activity":"com.yxcorp.gifshow.HomeActivity",
    "times": 1,
    "actions": [
        {
            "xpath":"//*[@resource-id='com.smile.gifmaker:id/left_btn']",
            "action": "CLICK",
            "throttle": 3000
        },
        {
            "xpath":"//*[@resource-id='com.smile.gifmaker:id/setting_iv']",
            "action": "CLICK",
            "throttle": 3000
        }
    ]
}
]

**Comment by zhangzhao4444** [comment]
请更新版本，再验证下
