### ISSUE TITLE
Fastbot设置事件类型比例无效

### ISSUE THREAD

**Issue by MangoHunter** [bytedance/Fastbot_Android#44]
adb -s 172.28.51.74 shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar exec app_process /system/bin com.android.commands.monkey.Monkey  -p <package-name> --pct-touch 50 --pct-motion 50 --agent robot --act-blacklist-file /sdcard/abl.strings --running-minutes 120 --throttle 1200 -v -v

在命令行中Touch事件和Motion事件，并且比例达到100%，可是在运行的时候仍会发送syskey事件。
请问各位大佬该如何解决。

**Comment by zhangzhao4444** [comment]
fastbot中没有事件比例的概念，通过ai方式决策
