### ISSUE TITLE
请问没有截图怎么解决呢？如何配置自动登录账号呢？

### ISSUE THREAD

**Issue by pingchaodeng** [bytedance/Fastbot_Android#51]

**Comment by zhangzhao4444** [comment]
2.2.01.0824.1351-git 再试一下，max.config中设置
max.takeScreenshot = true
max.takeScreenshotForEveryStep = true
--throttle > 400 且当前界面为待测app 才会截图

登陆可以参考用户手册中配置自定义事件 max.xpath.action

**Comment by pingchaodeng** [comment]
> 2.2.01.0824.1351-git 再试一下，max.config中设置 max.takeScreenshot = true max.takeScreenshotForEveryStep = true --throttle > 400 且当前界面为待测app 才会截图
> 
> 登陆可以参考用户手册中配置自定义事件 max.xpath.action

截图只有设置每一步的截图吗？能否只截取崩溃时的图片呢？
登录自定义事件无效呢。按照文档配置了步骤，运行的时候没有执行
