### ISSUE TITLE
无法生存日志

### ISSUE THREAD

**Issue by gegelaopiaoke** [bytedance/Fastbot_Android#6]
adb shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.stardust.kissreader --agent robot --running-minutes 5 --throttle 600 --bugreport  --output-directory /sdcard/Kisslog\crash -v -v

请问下作者大大，我保存文件的命令错了么，我只有文件件，没看到过log日志

**Comment by zhangzhao4444** [comment]
同学，你shell命令有错误。
