### ISSUE TITLE
配置schema后，启动后跳了一次，又回到首页了，无法测试跳转的schema

### ISSUE THREAD

**Issue by chongbo2013** [bytedance/Fastbot_Android#60]
配置schema后，启动后跳了一次，又回到首页了，无法测试跳转的schema。
谢谢！修复下哈，

**Comment by geron-cn** [comment]
期望是一直在这个 scheme 的页面运行吗，可以结合白名单一起使用
btw： 跳转之后的动作是不定的（也和 App 内部逻辑相关）

**Comment by chongbo2013** [comment]
我这边配置了，启动后 立刻跳到schema，但是又立刻返回到首页了，你的意思是说，我屏蔽首页是吗，这样就暂时不会返回到首页

**Comment by zhangzhao4444** [comment]
同学加下微信，了解下具体情况

**Comment by chongbo2013** [comment]
@zhangzhao4444 可以的私发你哈

**Comment by geron-cn** [comment]
@chongbo2013 hello， 这个问题解决了么， 加微信了吗，没收到呢

**Comment by chongbo2013** [comment]
@geron-cn 我记得我发你邮箱了，难怪这么就没回复哈

**Comment by qqtester** [comment]
请问这个问题如何解决的？我这里有一样的问题
