### ISSUE TITLE
启动命令运行没效果

### ISSUE THREAD

**Issue by dolphkon** [bytedance/Fastbot_Android#68]
* 问题描述：运行如下命令时要么直接跳转到leakcanary里面去，要么启动App 后命令就运行结束了，没发现什么报错信息。
* 命令如下：
`adb  shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.jlpay.merch  --agent reuseq --running-minutes 5 --throttle 600 -v -v`
* 说明：此命令开始能正常使用，在使用黑控件的过程中报错了，后回退发现此命令也用不了了。
* 日志链接：
https://preview-static.clewm.net/cli/view-doc/excel/index.html?url=https%3A%2F%2Fncstatic.clewm.net%2Frsrc%2F2021%2F0922%2F17%2F93be8bf5f25f539f9da7a81e1acdbade&copy=1&filename=logcat.log.txt&download=1&code=qnCEZoR&open=d90d23baeea34ad1bcdea78a4ceebe10&action=&_=1632304337787&frompc=false&org_id=30653521&web_url=http%3A%2F%2Fqr61.cn%2FoVUXzT%2FqnCEZoR&app=&shareUrl=&shareName=logcat.log.txt&shareCodeUrl=&auth_app_maps=&auth_maps=&auth_maps_publickey=&auth_maps_time=&surl=&free=1&uni=&collect=0&from=h5&show_collect=1&show_share=1&convert=1&fileext=txt

**Comment by geron-cn** [comment]
麻烦提供下 黑控件配置

**Comment by dolphkon** [comment]
* 黑控件配置

`[
{
    "activity":"com.jlpay.merch.ui.login.LoginActivity",
       "bounds": "[0,1583][1080,2288]"
},
{
    "activity":"com.jlpay.merch.ui.login.LoginActivity",
    "bounds": "[60,1311][1080,1418]"
},
{
    "activity":"com.jlpay.merch.ui.login.LoginActivity",
    "bounds": "[90,1142][1020,1199]"
},
{
    "activity":"com.jlpay.merch.ui.account.safetysetting.SettingActivity",
    "bounds": "[48,288][1032,445]"
},
{
    "activity":"com.jlpay.merch.ui.account.safetysetting.SettingActivity",
    "xpath": "//*[@resource-id='com.jlpay.merch:id/btn_loginout'and @text='退出登陆']"
}
]`

**Comment by geron-cn** [comment]
另： bounds 为 0.0~1.0 的一个百分比数值

**Comment by dolphkon** [comment]
bounds是怎么取值的呢？之前是通过uiautomatorviewer这个工具获取的

**Comment by geron-cn** [comment]
> bounds是怎么取值的呢？之前是通过uiautomatorviewer这个工具获取的

uiautomatorviewer 获取到值后除一下根结点（通常也是分辨率）的大小即可
