### ISSUE TITLE
adbkeyboard on，已匹配到node，但无法输入max.xpath.actions指定的text的内容，还是随机输入

### ISSUE THREAD

**Issue by HK714456322** [bytedance/Fastbot_Android#7]
![image](https://user-images.githubusercontent.com/32071770/103257573-b42df980-49cc-11eb-8490-5c72e2d5bab3.png)

![image](https://user-images.githubusercontent.com/32071770/103257519-7630d580-49cc-11eb-8c88-e1cf718126d9.png)

**Comment by zhangzhao4444** [comment]
机型是？ 看log有输入 sending input text ，是否有软键盘或输入保护？

**Comment by HK714456322** [comment]
华为P20、三星S9，maxim使用Appetizer检查校验驱动后是能正常输入的，但直接用maxim 命令和 fastbot_android的inputtext和click+text 都不行，直接使用adb input是可以输入的

**Comment by zhangzhao4444** [comment]
fastbot与max 自定义配置关键字不同的，看下是否配置错误？

**Comment by HK714456322** [comment]
[max.xpath.actions-fastbot_android.txt](https://github.com/bytedance/Fastbot_Android/files/5787098/max.xpath.actions-fastbot_android.txt)
[max.xpath.actions_maxim.txt](https://github.com/bytedance/Fastbot_Android/files/5787099/max.xpath.actions_maxim.txt)

**Comment by HK714456322** [comment]
maxim本地执行时的命令
adb shell "cd /sdcard ; rm -rf framework.jar monkey.jar"
adb shell "cd /sdcard ; ls -a |grep max | awk '{print $NF}'| xargs rm -rf "

adb push framework.jar /sdcard
adb push monkey.jar /sdcard

adb uninstall com.android.adbkeyboard
adb install -r ADBKeyBoard.apk
adb shell ime set com.android.adbkeyboard/.AdbIME


adb push max.xpath.actions /sdcard
adb push max.config /sdcard
adb push max.widget.black /sdcard
adb push max.xpath.selector /sdcard
adb push max.strings /sdcard

adb shell CLASSPATH=/sdcard/monkey.jar:/sdcard/framework.jar exec app_process /system/bin tv.panda.test.monkey.Monkey -p com.XXX.XXX --running-minutes 2 --throttle 800 --uiautomatortroy -v -v -v -v -v > debug_out/test.log 2> debug_out/err.txt & adb shell logcat -v time -d > debug_out/logcat.txt

**Comment by HK714456322** [comment]
[Uploading test_maxim_命令.log…]()

**Comment by HK714456322** [comment]
[Uploading CLB7N18807003968-logcat.log…]()

**Comment by HK714456322** [comment]
[XPU4C16B15007892-logcat.log](https://github.com/bytedance/Fastbot_Android/files/5795995/XPU4C16B15007892-logcat.log)
[Uploading CLB7N18807003968-logcat.log…]()

**Comment by lxh1121** [comment]
> [XPU4C16B15007892-logcat.log](https://github.com/bytedance/Fastbot_Android/files/5795995/XPU4C16B15007892-logcat.log)
> Uploading CLB7N18807003968-logcat.log…
请问这个问题你解决了？想请教一下

**Comment by zhourui0430** [comment]
@HK714456322 请教一下ADBKeyBoard怎么配置的

**Comment by zhangzhao4444** [comment]
更新下版本看问题还能复现吗？
