### ISSUE TITLE
黑区域配置后没效果

### ISSUE THREAD

**Issue by dolphkon** [bytedance/Fastbot_Android#70]
* 问题描述：在添加黑区域的时候，bounds是如何取值的呢？我这边根据uiautomatorviewer这个工具获取bounds的值，但是发现黑区域配置没效果。
* 附上我的黑区域配置文件代码：

> [
{
    "activity":"XXX.ui.login.LoginActivity",
       "bounds": "[0,1583][1080,2288]"
},
{
    "activity":"XXX.ui.login.LoginActivity",
    "bounds": "[60,1311][1080,1418]"
},
{
    "activity":"XXX..ui.login.LoginActivity",
    "bounds": "[90,1142][1020,1199]"
},
{
    "activity":"XXX..ui.account.safetysetting.SettingActivity",
    "bounds": "[48,288][1032,445]"
},
{
    "activity":"XXX..ui.account.safetysetting.SettingActivity",
    "xpath": "//*[@resource-id='com.jlpay.merch:id/btn_loginout'and @text='退出登陆']"
}
]

**Comment by geron-cn** [comment]
bounds 为四个 0.0 ~ 1.0 范围内的一个百分比数值，分别表示 左上和右下两个坐标
