### ISSUE TITLE
请问安卓支持多设备并行执行吗？

### ISSUE THREAD

**Issue by luoting0323** [bytedance/Fastbot_Android#71]
虚心求教，期待解答，感谢！！！
就是执行一次monkey，多个设备并行去跑。因为实际稳定性测试过程中，不可能只跑一台设备，我们有20+的在线设备可以提供来执行稳定性测试。但目前我看只能用-s指定单台去跑，并不能让所有在线设备并行去执行，或者指定部分在线设备去执行。

有没有类似--device device1 device2 xxx这样的参数。这样就能直接指定多个设备去跑了。
除了开多个终端的这种办法。

如果可以支持的话，那稳定性测试的效率会提高很多。

下面是我有多个在线设备运行时的报错：
![image](https://user-images.githubusercontent.com/56343996/134471491-37d5c83a-59ea-402d-87bd-107f42abb8aa.png)

**Comment by geron-cn** [comment]
可以， 由 adb -s  指定设备运行， 多次执行多条指令即可。
