### ISSUE TITLE
【前置登录】配置文件读取成功，但没有执行input

### ISSUE THREAD

**Issue by zhourui0430** [bytedance/Fastbot_Android#72]
![image](https://user-images.githubusercontent.com/79702879/134612297-1fc07b6e-be96-4bb1-8feb-ce0853bf3ac2.png)

**Comment by zhourui0430** [comment]
还发现、好像没有优先执行配置文件、而是先进行了随机操作、在读取配置文件的中间过程中、也有在执行随机点击操作

**Comment by geron-cn** [comment]
检查下是否使用的是 adb keyboard

**Comment by zhourui0430** [comment]
@geron-cn 感谢！问题已解决，的确是由于AdbKeyBoard未开启造成

**Comment by pingchaodeng** [comment]
> @geron-cn 感谢！问题已解决，的确是由于AdbKeyBoard未开启造成

你好，请问前置登录如何配置呢？
