### ISSUE TITLE
遇到Crash或者ANR是否可以自动截图？

### ISSUE THREAD

**Issue by sww0825521xy** [bytedance/Fastbot_Android#73]

**Comment by zhangzhao4444** [comment]
目前Fastbot支持了单步截图和崩溃捕获，可以自行外部开发脚本结合崩溃的时间戳和截图看是否构建崩溃点前的截图？同学看看是否已经满足需求？

**Comment by sww0825521xy** [comment]
> 目前Fastbot支持了单步截图和崩溃捕获，可以自行外部开发脚本结合崩溃的时间戳和截图看是否构建崩溃点前的截图？同学看看是否已经满足需求？

增加了如下配置，--throttle 500，然后push到sdcard下面，android12上不生效
max.takeScreenshot = true
**max.takeScreenshotForEveryStep = false**
max.saveGUITreeToXmlEveryStep =true
