### ISSUE TITLE
awl.strings 配置后执行未生效

### ISSUE THREAD

**Issue by ch3265936** [bytedance/Fastbot_Android#75]
1、push. .*jar和 libs.*和awl.strings(配置a b c 页面)
2、执行过程依然跑到除了abc之外的页面，是否需要添加其他配置文件？单纯配置白名单可否达到只允许名单内页面功能？

**Comment by ch3265936** [comment]
adb shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p tv.danmaku.bili --agent reuseq --act-whitelist-file /sdcard/awl.strings --running-minutes 10 --throttle 300 -v -v

**Comment by zhangzhao4444** [comment]
除了abc之外的页面是launcher或app主页吗？ 目前的机制是launcher和主页会默认加白，否则app崩溃后就无法启动了。 如果是的话，跳转到主页可以在主页中配置100%概率的自定义事件再引导到abc中
