### ISSUE TITLE
开启高速截图时未保存xml文件

### ISSUE THREAD

**Issue by dolphkon** [bytedance/Fastbot_Android#76]
* 问题描述：开启高速截图时没找到xml文件（sdcard卡目录下有截图）

* 说明：max.config 文件配置如下：
     

> max.takeScreenshot = true
max.takeScreenshotForEveryStep = true
max.saveGUITreeToXmlEveryStep =true

* 命令：

> adb  shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.jlpay.merch  --agent reuseq --running-minutes 20 --throttle 600 -v -v

**Comment by huhanGitHub** [comment]
我也遇到了一样的问题，设置了只保存截图，没有dump的xml文件

**Comment by zhangzhao4444** [comment]
fixed 2.2.01.1002.2151-git
