### ISSUE TITLE
使用文档错误

### ISSUE THREAD

**Issue by nostmabole** [bytedance/Fastbot_Android#77]
黑名单例句包含错误，缺少 ： 会抛异常。

adb -s 设备号 shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p 包名 --agent reuseq  --act-blacklist-file /sdcard/abl.strings --running-minutes 遍历时长 --throttle 事件频率 -v -v 

应添加个冒号，改为

adb -s 设备号 shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p 包名 --agent reuseq  --act-blacklist-file /sdcard/abl.strings --running-minutes 遍历时长 --throttle 事件频率 -v -v

**Comment by zhangzhao4444** [comment]
fixed

**Comment by zhangzhao4444** [comment]
fixed
