### ISSUE TITLE
ADBKeyBoard输入法无法正常输入文本

### ISSUE THREAD

**Issue by LYW010** [bytedance/Fastbot_Android#78]
正常配置ADBKeyBoard输入法并在手机端设置为默认输入法，手机端选中文本框后显示了ADB Keyboard {ON}，通过广播指令adb shell am broadcast -a ADB_INPUT_TEXT --es msg “...”能够输入目标英文或中文字符串，但是在自动化测试过程中工具尝试输入文本时日志显示Warning checkVirtualKeyboard: Input Only Once，并且无法自动输入文本。

**Comment by zhangzhao4444** [comment]
同学，你好，加下微信，录制段出问题视频

**Comment by mengdg** [comment]
我也遇到这个问题了，想问一下如何解决的

**Comment by ltDino** [comment]
您好，我也遇到这个问题了，没有办法自动输入文本

**Comment by zhangzhao4444** [comment]
2.3.23.0810.1705-git fixed
