### ISSUE TITLE
执行后的log有fastbot报错信息

### ISSUE THREAD

**Issue by ShenJiaojiao** [bytedance/Fastbot_Android#82]
[Fastbot][2021-10-14 14:50:09.707] // get activity api error
[Fastbot][2021-10-14 14:50:09.708] Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.chehejia.oc.m01/.view.gui.user.login.LoginActivity;end
[Fastbot][2021-10-14 14:50:09.709] IActivityManager.startactivity failed, execute am start activity
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.commands.monkey.framework.a.a(SourceFile:141)
	at com.android.commands.monkey.framework.a.a(SourceFile:209)
	at com.android.commands.monkey.framework.AndroidDevice.a(SourceFile:177)
	at com.android.commands.monkey.x.k(SourceFile:2411)
	at com.android.commands.monkey.Monkey.f(SourceFile:1501)
	at com.android.commands.monkey.Monkey.a(SourceFile:860)
	at com.android.commands.monkey.Monkey.main(SourceFile:454)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:342)
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:575)
	at android.app.IActivityManager$Stub$Proxy.getTasks(IActivityManager.java:5928)
	... 10 more
[Fastbot][2021-10-14 14:50:09.758] // get activity api error
[Fastbot][2021-10-14 14:50:09.759] Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.chehejia.oc.m01/.view.gui.user.login.LoginActivity;end
[Fastbot][2021-10-14 14:50:09.759] IActivityManager.startactivity failed, execute am start activity
[Fastbot][2021-10-14 14:50:09.800]     //[calendar_time:2021-10-14 14:50:09.800  system_uptime:509755072]
[Fastbot][2021-10-14 14:50:09.801]     // Sending event #485500

**Comment by ShenJiaojiao** [comment]
[](url)

**Comment by ShenJiaojiao** [comment]
还有oom

[1634193649274] *** Get guitree ***
[1634193655535] // Monkey is over!
[1634193655535] :Sending rotation degree : 0, persist : false
[1634193655549] Running failed
java.lang.OutOfMemoryError: Failed to allocate a 33576 byte allocation with 11984 free bytes and 11KB until OOM, target footprint 268435456, growth limit 268435456
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
	at java.lang.StringBuffer.toString(StringBuffer.java:671)
	at java.io.StringWriter.toString(StringWriter.java:210)
	at com.android.a.d.a.cc(SourceFile:170)
	at com.android.a.a.e.c(SourceFile:2263)
	at com.android.a.a.b.b(SourceFile:236)
	at com.android.a.a.b.a(SourceFile:226)
	at com.android.commands.monkey.y.y(SourceFile:681)
	at com.android.commands.monkey.y.l(SourceFile:1259)
	at com.android.commands.monkey.Monkey.f(SourceFile:1861)
	at com.android.commands.monkey.Monkey.a(SourceFile:1105)
	at com.android.commands.monkey.Monkey.main(SourceFile:827)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
[1634193656316] Please report this bug issue to github

**Comment by geron-cn** [comment]
> 还有oom
> 
> [1634193649274] *** Get guitree *** [1634193655535] // Monkey is over! [1634193655535] :Sending rotation degree : 0, persist : false [1634193655549] Running failed java.lang.OutOfMemoryError: Failed to allocate a 33576 byte allocation with 11984 free bytes and 11KB until OOM, target footprint 268435456, growth limit 268435456 at java.lang.StringFactory.newStringFromChars(StringFactory.java:260) at java.lang.StringBuffer.toString(StringBuffer.java:671) at java.io.StringWriter.toString(StringWriter.java:210) at com.android.a.d.a.cc(SourceFile:170) at com.android.a.a.e.c(SourceFile:2263) at com.android.a.a.b.b(SourceFile:236) at com.android.a.a.b.a(SourceFile:226) at com.android.commands.monkey.y.y(SourceFile:681) at com.android.commands.monkey.y.l(SourceFile:1259) at com.android.commands.monkey.Monkey.f(SourceFile:1861) at com.android.commands.monkey.Monkey.a(SourceFile:1105) at com.android.commands.monkey.Monkey.main(SourceFile:827) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380) [1634193656316] Please report this bug issue to github

OOM 拉新最新版本已修复（注意查看 readme 启动命令和环境准备稍有更新）

**Comment by ShenJiaojiao** [comment]
> > 还有oom
> > [1634193649274] *** Get guitree *** [1634193655535] // Monkey is over! [1634193655535] :Sending rotation degree : 0, persist : false [1634193655549] Running failed java.lang.OutOfMemoryError: Failed to allocate a 33576 byte allocation with 11984 free bytes and 11KB until OOM, target footprint 268435456, growth limit 268435456 at java.lang.StringFactory.newStringFromChars(StringFactory.java:260) at java.lang.StringBuffer.toString(StringBuffer.java:671) at java.io.StringWriter.toString(StringWriter.java:210) at com.android.a.d.a.cc(SourceFile:170) at com.android.a.a.e.c(SourceFile:2263) at com.android.a.a.b.b(SourceFile:236) at com.android.a.a.b.a(SourceFile:226) at com.android.commands.monkey.y.y(SourceFile:681) at com.android.commands.monkey.y.l(SourceFile:1259) at com.android.commands.monkey.Monkey.f(SourceFile:1861) at com.android.commands.monkey.Monkey.a(SourceFile:1105) at com.android.commands.monkey.Monkey.main(SourceFile:827) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380) [1634193656316] Please report this bug issue to github
> 
> OOM 拉新最新版本已修复（注意查看 readme 启动命令和环境准备稍有更新）

hi ,运行前环境准备中的jar和lib下的文件已经push到sdcard。
运行命令也已经更新。
adb -s 3HX0217301001925 shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.chehejia.oc.m01  --agent reuseq --throttle 100 --running-minutes 2000 -v -v --bugreport --output-directory /sdcard/maximlog

还是会提示oom，还有找不到activity api的两种错误日志

**Comment by geron-cn** [comment]
> > > 还有oom
> > > [1634193649274] *** Get guitree *** [1634193655535] // Monkey is over! [1634193655535] :Sending rotation degree : 0, persist : false [1634193655549] Running failed java.lang.OutOfMemoryError: Failed to allocate a 33576 byte allocation with 11984 free bytes and 11KB until OOM, target footprint 268435456, growth limit 268435456 at java.lang.StringFactory.newStringFromChars(StringFactory.java:260) at java.lang.StringBuffer.toString(StringBuffer.java:671) at java.io.StringWriter.toString(StringWriter.java:210) at com.android.a.d.a.cc(SourceFile:170) at com.android.a.a.e.c(SourceFile:2263) at com.android.a.a.b.b(SourceFile:236) at com.android.a.a.b.a(SourceFile:226) at com.android.commands.monkey.y.y(SourceFile:681) at com.android.commands.monkey.y.l(SourceFile:1259) at com.android.commands.monkey.Monkey.f(SourceFile:1861) at com.android.commands.monkey.Monkey.a(SourceFile:1105) at com.android.commands.monkey.Monkey.main(SourceFile:827) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380) [1634193656316] Please report this bug issue to github
> > 
> > 
> > OOM 拉新最新版本已修复（注意查看 readme 启动命令和环境准备稍有更新）
> 
> hi ,运行前环境准备中的jar和lib下的文件已经push到sdcard。 运行命令也已经更新。 adb -s 3HX0217301001925 shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.chehejia.oc.m01 --agent reuseq --throttle 100 --running-minutes 2000 -v -v --bugreport --output-directory /sdcard/maximlog
> 
> 还是会提示oom，还有找不到activity api的两种错误日志

根据这个log初步判断你还是使用的老版本，  麻烦贴下完整的日志文件和 运行时的  `adb shell logcat | grep Fastbot`。

**Comment by ShenJiaojiao** [comment]
> > > > 还有oom
> > > > [1634193649274] *** Get guitree *** [1634193655535] // Monkey is over! [1634193655535] :Sending rotation degree : 0, persist : false [1634193655549] Running failed java.lang.OutOfMemoryError: Failed to allocate a 33576 byte allocation with 11984 free bytes and 11KB until OOM, target footprint 268435456, growth limit 268435456 at java.lang.StringFactory.newStringFromChars(StringFactory.java:260) at java.lang.StringBuffer.toString(StringBuffer.java:671) at java.io.StringWriter.toString(StringWriter.java:210) at com.android.a.d.a.cc(SourceFile:170) at com.android.a.a.e.c(SourceFile:2263) at com.android.a.a.b.b(SourceFile:236) at com.android.a.a.b.a(SourceFile:226) at com.android.commands.monkey.y.y(SourceFile:681) at com.android.commands.monkey.y.l(SourceFile:1259) at com.android.commands.monkey.Monkey.f(SourceFile:1861) at com.android.commands.monkey.Monkey.a(SourceFile:1105) at com.android.commands.monkey.Monkey.main(SourceFile:827) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380) [1634193656316] Please report this bug issue to github
> > > 
> > > 
> > > OOM 拉新最新版本已修复（注意查看 readme 启动命令和环境准备稍有更新）
> > 
> > 
> > hi ,运行前环境准备中的jar和lib下的文件已经push到sdcard。 运行命令也已经更新。 adb -s 3HX0217301001925 shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.chehejia.oc.m01 --agent reuseq --throttle 100 --running-minutes 2000 -v -v --bugreport --output-directory /sdcard/maximlog
> > 还是会提示oom，还有找不到activity api的两种错误日志
> 
> 根据这个log初步判断你还是使用的老版本， 麻烦贴下完整的日志文件和 运行时的 `adb shell logcat | grep Fastbot`。

输出日志：链接: https://pan.baidu.com/s/1x3eE9EKtVD-lUEEr6RLBDg  密码: ulf7
运行时的可能没有了，已经又开始跑了

**Comment by ShenJiaojiao** [comment]
> > > > > 还有oom
> > > > > [1634193649274] *** Get guitree *** [1634193655535] // Monkey is over! [1634193655535] :Sending rotation degree : 0, persist : false [1634193655549] Running failed java.lang.OutOfMemoryError: Failed to allocate a 33576 byte allocation with 11984 free bytes and 11KB until OOM, target footprint 268435456, growth limit 268435456 at java.lang.StringFactory.newStringFromChars(StringFactory.java:260) at java.lang.StringBuffer.toString(StringBuffer.java:671) at java.io.StringWriter.toString(StringWriter.java:210) at com.android.a.d.a.cc(SourceFile:170) at com.android.a.a.e.c(SourceFile:2263) at com.android.a.a.b.b(SourceFile:236) at com.android.a.a.b.a(SourceFile:226) at com.android.commands.monkey.y.y(SourceFile:681) at com.android.commands.monkey.y.l(SourceFile:1259) at com.android.commands.monkey.Monkey.f(SourceFile:1861) at com.android.commands.monkey.Monkey.a(SourceFile:1105) at com.android.commands.monkey.Monkey.main(SourceFile:827) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380) [1634193656316] Please report this bug issue to github
> > > > 
> > > > 
> > > > OOM 拉新最新版本已修复（注意查看 readme 启动命令和环境准备稍有更新）
> > > 
> > > 
> > > hi ,运行前环境准备中的jar和lib下的文件已经push到sdcard。 运行命令也已经更新。 adb -s 3HX0217301001925 shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.chehejia.oc.m01 --agent reuseq --throttle 100 --running-minutes 2000 -v -v --bugreport --output-directory /sdcard/maximlog
> > > 还是会提示oom，还有找不到activity api的两种错误日志
> > 
> > 
> > 根据这个log初步判断你还是使用的老版本， 麻烦贴下完整的日志文件和 运行时的 `adb shell logcat | grep Fastbot`。
> 
> 输出日志：链接: https://pan.baidu.com/s/1x3eE9EKtVD-lUEEr6RLBDg 密码: ulf7 运行时的可能没有了，已经又开始跑了

如果今晚再出现，会提交一下运行时的日志

**Comment by geron-cn** [comment]
resolved:   确认问题为 版本未更新。
