### ISSUE TITLE
max.xpath.actions如下,运行起来没有操作如下步骤

### ISSUE THREAD

**Issue by zhanghao921** [bytedance/Fastbot_Android#86]
[
{
    "prob": 1,
    "activity":"com.xueqiu.android.main.view.MainActivity",
    "times": 1,
    "actions": [
        {
            "xpath":'//*[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[7]',
            "action": "CLICK",
            "throttle": 500
        },
		{
            "xpath":'//*[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[6]',
            "action": "CLICK",
            "throttle": 500
        },
		{
            "xpath":'//*[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[5]',
            "action": "CLICK",
            "throttle": 500
        },
		{
            "xpath":'//*[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[4]',
            "action": "CLICK",
            "throttle": 500
        }
    ]
}
]

**Comment by iwome** [comment]
你现在可以了吗。我发现我这个设置好像也是无效。//后面文档是是有“*”的

**Comment by ShenJiaojiao** [comment]
> [ { "prob": 1, "activity":"com.xueqiu.android.main.view.MainActivity", "times": 1, "actions": [ { "xpath":'//_[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[7]', "action": "CLICK", "throttle": 500 }, { "xpath":'//_[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[6]', "action": "CLICK", "throttle": 500 }, { "xpath":'//_[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[5]', "action": "CLICK", "throttle": 500 }, { "xpath":'//_[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[4]', "action": "CLICK", "throttle": 500 } ] } ]

一般都是配置的不对，这个脚本是可以正常执行的

**Comment by geron-cn** [comment]
> [
> {
> "prob": 1,
> "activity":"com.xueqiu.android.main.view.MainActivity",
> "times": 1,
> "actions": [
> {
> "xpath":'//_[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[7]', "action": "CLICK", "throttle": 500 }, { "xpath":'//_[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[6]',
> "action": "CLICK",
> "throttle": 500
> },
> {
> "xpath":'//_[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[5]', "action": "CLICK", "throttle": 500 }, { "xpath":'//_[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[4]',
> "action": "CLICK",
> "throttle": 500
> }
> ]
> }
> ]

使用 json.cn 等 format 工具检测配置， 你这个配置是错的。

**Comment by pingchaodeng** [comment]
> > [
> > {
> > "prob": 1,
> > "activity":"com.xueqiu.android.main.view.MainActivity",
> > "times": 1,
> > "actions": [
> > {
> > "xpath":'//_[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[7]', "action": "CLICK", "throttle": 500 }, { "xpath":'//_[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[6]',
> > "action": "CLICK",
> > "throttle": 500
> > },
> > {
> > "xpath":'//_[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[5]', "action": "CLICK", "throttle": 500 }, { "xpath":'//_[@resource-id="com.dangbei.TVHomeLauncher:id/activity_main_header_tab_rv"]/android.widget.RelativeLayout[4]',
> > "action": "CLICK",
> > "throttle": 500
> > }
> > ]
> > }
> > ]
> 
> 使用 json.cn 等 format 工具检测配置， 你这个配置是错的。

使用Jason.cn检查无问题的配置，也无法正常执行，请问是什么原因呢@geron-cn
