### ISSUE TITLE
对单个App进行测试，跑到后面，会一直对通知快捷开关来回操作。

### ISSUE THREAD

**Issue by Hanlen520** [bytedance/Fastbot_Android#87]
附件是测试log和录屏。
![target-06039330BT006122_2021-10-19_10-34-02-51](https://user-images.githubusercontent.com/35830128/137835545-96403764-3040-445f-a4b5-2a1e9390df99.gif)
[fastbot_log.txt](https://github.com/bytedance/Fastbot_Android/files/7369781/fastbot_log.txt)

**Comment by geron-cn** [comment]
问题已修复， 预期近期发布， 持续关注验证。

**Comment by zhangzhao4444** [comment]
已优化并发布
