### ISSUE TITLE
abl.strings设置黑名单 无效

### ISSUE THREAD

**Issue by iwome** [bytedance/Fastbot_Android#88]
![image](https://user-images.githubusercontent.com/19374952/138021602-925efaf6-8eee-4264-91b0-efae2b3715fa.png)

**Comment by geron-cn** [comment]
麻烦确认下
1. 启动命令是否添加黑名单
2. 配置 activity 是否匹配（包含空白字符等）

**Comment by iwome** [comment]
是可以的。启动命令里黑名单以为加了，然后没加上去

**Comment by startimesqa** [comment]
我遇到了同样的问题，看打出来的日志，明明有拿到blacklist，但是就是仍然还是会进入且会各种操作
另外，现在是不是不需要在命令行中指定参数了，直接会读取黑白名单的文件，是吧？

**Comment by superWenshuo** [comment]
没人维护了，确实还会进入，而且指定黑名单元素 也会点击到...各种坑，但是比原生monkey好用
