### ISSUE TITLE
文本输入有问题，输入不进去

### ISSUE THREAD

**Issue by iwome** [bytedance/Fastbot_Android#89]
[Fastbot][2021-10-20 11:27:57.267] Input text is abc123123 。
PS 问题好像有点多。主要是输入和其他自定义配置

**Comment by iwome** [comment]
有个日志，和这个有关系吗？[Fastbot]*** WARNING *** checkVirtualKeyboard: Input only once.

**Comment by iwome** [comment]
随机输入无效。一直点输入框，就是不输入

**Comment by GG-liuzh** [comment]
> 随机输入无效。一直点输入框，就是不输入

大哥，你解决了吗 @iwome
