### ISSUE TITLE
max.xpath.actions里设置输入内容，同时已经设置了adbkeyboard模式了，但是内容未输入

### ISSUE THREAD

**Issue by pxrgod** [bytedance/Fastbot_Android#90]
[Fastbot][2021-10-21 16:53:16.438] action type: CLICK
[Fastbot][2021-10-21 16:53:16.439] rpc cost time: 4
[Fastbot][2021-10-21 16:53:16.470] Input text is 123123
[Fastbot][2021-10-21 16:53:16.478]  event time:60
[Fastbot][2021-10-21 16:53:16.479] :Sending rotation degree=0, persist=false
[Fastbot][2021-10-21 16:53:16.519] :Sending Touch (ACTION_DOWN): 0:(484.5,741.5)
[Fastbot][2021-10-21 16:53:16.529] :Sending Touch (ACTION_UP): 0:(484.5,741.5)
[Fastbot][2021-10-21 16:53:16.535] :Checking IME Visible Height: 0
[Fastbot][2021-10-21 16:53:16.689] :Checking IME Visible Height: 53
[Fastbot][2021-10-21 16:53:16.990] :Sending Input (123123)

**Comment by geron-cn** [comment]
您好， 麻烦提供下版本，设备型号等， 完整log 🙏

**Comment by pxrgod** [comment]
这个是我没有设置好输入法的缘故发自我的华为手机-------- 原始邮件 --------发件人： gero ***@***.***>日期： 2021年10月26日周二 下午4:41收件人： bytedance/Fastbot_Android ***@***.***>抄送： pxrgod ***@***.***>, Author ***@***.***>主    题： Re: [bytedance/Fastbot_Android] max.xpath.actions里设置输入内容，同时已经设置了adbkeyboard模式了，但是内容未输入 (Issue #90)

您好， 麻烦提供下版本，设备型号等， 完整log 🙏

**Comment by zhangzhao4444** [comment]
激活输入法应该就可以了
