### ISSUE TITLE
自定义事件顺序没有成功

### ISSUE THREAD

**Issue by zhanghao921** [bytedance/Fastbot_Android#97]
[
{
    "prob": 1,
    "activity":"com.xueqiu.android.main.view.MainActivity",
    "times": 1,
    "actions": [
        {
            "xpath":"//*[@resource-id='com.xueqiu.android:id/title_text' and @text='推荐']",
            "action": "CLICK",
            "throttle": 1000
        },
		{
            "xpath":"//*[@resource-id='com.xueqiu.android:id/title_text' and @text='视频']",
            "action": "CLICK",
            "throttle": 1000
        },
		{
            "xpath":"//*[@resource-id='com.xueqiu.android:id/title_text' and @text='热榜']",
            "action": "CLICK",
            "throttle": 1000
        },
		{
            "xpath":"//*[@resource-id='com.xueqiu.android:id/title_text' and @text='嘉年华']",
            "action": "CLICK",
            "throttle": 1000
        }
    ]
}
]

max.xpath.actions的配置是没有问题的，导航栏“推荐”，“视频”这些元素实际是可以点击的，但是属性值里面显示clickable为false（不知道为啥界面几乎都可以点击的元素clickable都设置为false），是不是因为这个原因，导致没遍历到？
![image](https://user-images.githubusercontent.com/85275626/139374156-c51aa22e-7e59-4b80-b42d-1a2999dd6cd1.png)

**Comment by zhangzhao4444** [comment]
同学，帮把运行这段自定义事件的 logcat 发一下，thx

**Comment by zhanghao921** [comment]
[1104.log](https://github.com/bytedance/Fastbot_Android/files/7475890/1104.log)

**Comment by zhangzhao4444** [comment]
同学，不是这个log，是这个自定义事件运行过程中的logcat

**Comment by zhanghao921** [comment]
有数据
